<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhGenero', 'doctrine');

/**
 * BasetdhGenero
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Secciones
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getSecciones() Returns the current record's "Secciones" collection
 * @method tdhGenero           setId()        Sets the current record's "id" value
 * @method tdhGenero           setNombre()    Sets the current record's "nombre" value
 * @method tdhGenero           setSecciones() Sets the current record's "Secciones" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhGenero extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_genero');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('tdhSeccion as Secciones', array(
             'local' => 'id',
             'foreign' => 'genero_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}