<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhPopular', 'doctrine');

/**
 * BasetdhPopular
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $visitas
 * @property date $fecha
 * @property integer $seccion_id
 * @property tdhSeccion $Seccion
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getVisitas()    Returns the current record's "visitas" value
 * @method date       getFecha()      Returns the current record's "fecha" value
 * @method integer    getSeccionId()  Returns the current record's "seccion_id" value
 * @method tdhSeccion getSeccion()    Returns the current record's "Seccion" value
 * @method tdhPopular setId()         Sets the current record's "id" value
 * @method tdhPopular setVisitas()    Sets the current record's "visitas" value
 * @method tdhPopular setFecha()      Sets the current record's "fecha" value
 * @method tdhPopular setSeccionId()  Sets the current record's "seccion_id" value
 * @method tdhPopular setSeccion()    Sets the current record's "Seccion" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhPopular extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_popular');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('visitas', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('seccion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tdhSeccion as Seccion', array(
             'local' => 'seccion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}