<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhAsociacionInvitacion', 'doctrine');

/**
 * BasetdhAsociacionInvitacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $asociacion_id
 * @property boolean $es_de_usuario
 * @property ehAuthUser $Usuario
 * @property tdhAsociacion $Asociacion
 * 
 * @method integer                 getUsuarioId()     Returns the current record's "usuario_id" value
 * @method integer                 getAsociacionId()  Returns the current record's "asociacion_id" value
 * @method boolean                 getEsDeUsuario()   Returns the current record's "es_de_usuario" value
 * @method ehAuthUser              getUsuario()       Returns the current record's "Usuario" value
 * @method tdhAsociacion           getAsociacion()    Returns the current record's "Asociacion" value
 * @method tdhAsociacionInvitacion setUsuarioId()     Sets the current record's "usuario_id" value
 * @method tdhAsociacionInvitacion setAsociacionId()  Sets the current record's "asociacion_id" value
 * @method tdhAsociacionInvitacion setEsDeUsuario()   Sets the current record's "es_de_usuario" value
 * @method tdhAsociacionInvitacion setUsuario()       Sets the current record's "Usuario" value
 * @method tdhAsociacionInvitacion setAsociacion()    Sets the current record's "Asociacion" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhAsociacionInvitacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_asociacion_invitacion');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('asociacion_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('es_de_usuario', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhAsociacion as Asociacion', array(
             'local' => 'asociacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}