<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhConsultaRespuesta', 'doctrine');

/**
 * BasetdhConsultaRespuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property string $ip
 * @property integer $usuario_id
 * @property integer $consulta_id
 * @property ehAuthUser $Usuario
 * @property tdhConsulta $Consulta
 * 
 * @method integer              getId()          Returns the current record's "id" value
 * @method string               getDescripcion() Returns the current record's "descripcion" value
 * @method string               getIp()          Returns the current record's "ip" value
 * @method integer              getUsuarioId()   Returns the current record's "usuario_id" value
 * @method integer              getConsultaId()  Returns the current record's "consulta_id" value
 * @method ehAuthUser           getUsuario()     Returns the current record's "Usuario" value
 * @method tdhConsulta          getConsulta()    Returns the current record's "Consulta" value
 * @method tdhConsultaRespuesta setId()          Sets the current record's "id" value
 * @method tdhConsultaRespuesta setDescripcion() Sets the current record's "descripcion" value
 * @method tdhConsultaRespuesta setIp()          Sets the current record's "ip" value
 * @method tdhConsultaRespuesta setUsuarioId()   Sets the current record's "usuario_id" value
 * @method tdhConsultaRespuesta setConsultaId()  Sets the current record's "consulta_id" value
 * @method tdhConsultaRespuesta setUsuario()     Sets the current record's "Usuario" value
 * @method tdhConsultaRespuesta setConsulta()    Sets the current record's "Consulta" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhConsultaRespuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_consulta_respuesta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 4000,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '127.0.0.1',
             'length' => 255,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('consulta_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhConsulta as Consulta', array(
             'local' => 'consulta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}