<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhRecursoFavorito', 'doctrine');

/**
 * BasetdhRecursoFavorito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $recurso_id
 * 
 * @method integer            getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer            getRecursoId()  Returns the current record's "recurso_id" value
 * @method tdhRecursoFavorito setUsuarioId()  Sets the current record's "usuario_id" value
 * @method tdhRecursoFavorito setRecursoId()  Sets the current record's "recurso_id" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhRecursoFavorito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_recurso_favorito');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('recurso_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}