<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhAsociacionBusqueda', 'doctrine');

/**
 * BasetdhAsociacionBusqueda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property string $localidad
 * @property ehAuthUser $Usuario
 * 
 * @method integer               getId()         Returns the current record's "id" value
 * @method integer               getUsuarioId()  Returns the current record's "usuario_id" value
 * @method string                getLocalidad()  Returns the current record's "localidad" value
 * @method ehAuthUser            getUsuario()    Returns the current record's "Usuario" value
 * @method tdhAsociacionBusqueda setId()         Sets the current record's "id" value
 * @method tdhAsociacionBusqueda setUsuarioId()  Sets the current record's "usuario_id" value
 * @method tdhAsociacionBusqueda setLocalidad()  Sets the current record's "localidad" value
 * @method tdhAsociacionBusqueda setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhAsociacionBusqueda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_asociacion_busqueda');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('localidad', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $ehutilesmarkuptohtmlbehavior0 = new ehUtilesMarkupToHtmlBehavior(array(
             'field' => 'descripcion',
             'target' => 'descripcion_html',
             'parsers' => 
             array(
              'html' => false,
              'markdown' => true,
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($ehutilesmarkuptohtmlbehavior0);
    }
}