<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhConsultaTipoUsuario', 'doctrine');

/**
 * BasetdhConsultaTipoUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $tipo_id
 * 
 * @method integer                getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer                getTipoId()     Returns the current record's "tipo_id" value
 * @method tdhConsultaTipoUsuario setUsuarioId()  Sets the current record's "usuario_id" value
 * @method tdhConsultaTipoUsuario setTipoId()     Sets the current record's "tipo_id" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhConsultaTipoUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_consulta_tipo_usuario');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipo_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}