<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhFeedExterno', 'doctrine');

/**
 * BasetdhFeedExterno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $url_feed
 * @property string $url_web
 * 
 * @method integer        getId()       Returns the current record's "id" value
 * @method string         getNombre()   Returns the current record's "nombre" value
 * @method string         getUrlFeed()  Returns the current record's "url_feed" value
 * @method string         getUrlWeb()   Returns the current record's "url_web" value
 * @method tdhFeedExterno setId()       Sets the current record's "id" value
 * @method tdhFeedExterno setNombre()   Sets the current record's "nombre" value
 * @method tdhFeedExterno setUrlFeed()  Sets the current record's "url_feed" value
 * @method tdhFeedExterno setUrlWeb()   Sets the current record's "url_web" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhFeedExterno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_feed_externo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('url_feed', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('url_web', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}