<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhRecurso', 'doctrine');

/**
 * BasetdhRecurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $estado_aprobado
 * @property boolean $acepta_donativos
 * @property integer $favoritos
 * @property string $paypal
 * @property string $entradilla
 * @property string $autor
 * @property string $contacto_autor
 * @property integer $num_donativos
 * @property integer $cantidad_donativos
 * @property boolean $tiene_html
 * @property boolean $conver_pdf
 * @property boolean $conver_epub
 * @property boolean $separar_capitulos
 * @property integer $tipo_id
 * @property integer $seccion_id
 * @property integer $licencia_id
 * @property integer $hilo_id
 * @property ehForoHilo $Hilo
 * @property tdhSeccion $Seccion
 * @property tdhRecursoTipo $Tipo
 * @property tdhLicencia $Licencia
 * @property Doctrine_Collection $FavoritoDeUsuarios
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method boolean             getEstadoAprobado()     Returns the current record's "estado_aprobado" value
 * @method boolean             getAceptaDonativos()    Returns the current record's "acepta_donativos" value
 * @method integer             getFavoritos()          Returns the current record's "favoritos" value
 * @method string              getPaypal()             Returns the current record's "paypal" value
 * @method string              getEntradilla()         Returns the current record's "entradilla" value
 * @method string              getAutor()              Returns the current record's "autor" value
 * @method string              getContactoAutor()      Returns the current record's "contacto_autor" value
 * @method integer             getNumDonativos()       Returns the current record's "num_donativos" value
 * @method integer             getCantidadDonativos()  Returns the current record's "cantidad_donativos" value
 * @method boolean             getTieneHtml()          Returns the current record's "tiene_html" value
 * @method boolean             getConverPdf()          Returns the current record's "conver_pdf" value
 * @method boolean             getConverEpub()         Returns the current record's "conver_epub" value
 * @method boolean             getSepararCapitulos()   Returns the current record's "separar_capitulos" value
 * @method integer             getTipoId()             Returns the current record's "tipo_id" value
 * @method integer             getSeccionId()          Returns the current record's "seccion_id" value
 * @method integer             getLicenciaId()         Returns the current record's "licencia_id" value
 * @method integer             getHiloId()             Returns the current record's "hilo_id" value
 * @method ehForoHilo          getHilo()               Returns the current record's "Hilo" value
 * @method tdhSeccion          getSeccion()            Returns the current record's "Seccion" value
 * @method tdhRecursoTipo      getTipo()               Returns the current record's "Tipo" value
 * @method tdhLicencia         getLicencia()           Returns the current record's "Licencia" value
 * @method Doctrine_Collection getFavoritoDeUsuarios() Returns the current record's "FavoritoDeUsuarios" collection
 * @method tdhRecurso          setId()                 Sets the current record's "id" value
 * @method tdhRecurso          setEstadoAprobado()     Sets the current record's "estado_aprobado" value
 * @method tdhRecurso          setAceptaDonativos()    Sets the current record's "acepta_donativos" value
 * @method tdhRecurso          setFavoritos()          Sets the current record's "favoritos" value
 * @method tdhRecurso          setPaypal()             Sets the current record's "paypal" value
 * @method tdhRecurso          setEntradilla()         Sets the current record's "entradilla" value
 * @method tdhRecurso          setAutor()              Sets the current record's "autor" value
 * @method tdhRecurso          setContactoAutor()      Sets the current record's "contacto_autor" value
 * @method tdhRecurso          setNumDonativos()       Sets the current record's "num_donativos" value
 * @method tdhRecurso          setCantidadDonativos()  Sets the current record's "cantidad_donativos" value
 * @method tdhRecurso          setTieneHtml()          Sets the current record's "tiene_html" value
 * @method tdhRecurso          setConverPdf()          Sets the current record's "conver_pdf" value
 * @method tdhRecurso          setConverEpub()         Sets the current record's "conver_epub" value
 * @method tdhRecurso          setSepararCapitulos()   Sets the current record's "separar_capitulos" value
 * @method tdhRecurso          setTipoId()             Sets the current record's "tipo_id" value
 * @method tdhRecurso          setSeccionId()          Sets the current record's "seccion_id" value
 * @method tdhRecurso          setLicenciaId()         Sets the current record's "licencia_id" value
 * @method tdhRecurso          setHiloId()             Sets the current record's "hilo_id" value
 * @method tdhRecurso          setHilo()               Sets the current record's "Hilo" value
 * @method tdhRecurso          setSeccion()            Sets the current record's "Seccion" value
 * @method tdhRecurso          setTipo()               Sets the current record's "Tipo" value
 * @method tdhRecurso          setLicencia()           Sets the current record's "Licencia" value
 * @method tdhRecurso          setFavoritoDeUsuarios() Sets the current record's "FavoritoDeUsuarios" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhRecurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_recurso');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_aprobado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('acepta_donativos', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('favoritos', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('paypal', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('entradilla', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('autor', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('contacto_autor', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('num_donativos', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('cantidad_donativos', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('tiene_html', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('conver_pdf', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('conver_epub', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('separar_capitulos', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('tipo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('seccion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('licencia_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('hilo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehForoHilo as Hilo', array(
             'local' => 'hilo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhSeccion as Seccion', array(
             'local' => 'seccion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhRecursoTipo as Tipo', array(
             'local' => 'tipo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhLicencia as Licencia', array(
             'local' => 'licencia_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ehAuthUser as FavoritoDeUsuarios', array(
             'refClass' => 'tdhRecursoFavorito',
             'local' => 'recurso_id',
             'foreign' => 'usuario_id',
             'onDelete' => 'CASCADE'));
    }
}