<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhSorteo', 'doctrine');

/**
 * BasetdhSorteo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $estado_visible
 * @property boolean $estado_abierto
 * @property string $nombre
 * @property string $entradilla
 * @property string $aclaraciones
 * @property string $mensaje
 * @property timestamp $desde
 * @property timestamp $hasta
 * @property string $sufijo
 * @property string $url
 * @property integer $semilla
 * @property integer $participantes_min
 * @property integer $participantes_max
 * @property integer $participantes_num
 * @property Doctrine_Collection $Participantes
 * @property Doctrine_Collection $Condiciones
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method boolean             getEstadoVisible()     Returns the current record's "estado_visible" value
 * @method boolean             getEstadoAbierto()     Returns the current record's "estado_abierto" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method string              getEntradilla()        Returns the current record's "entradilla" value
 * @method string              getAclaraciones()      Returns the current record's "aclaraciones" value
 * @method string              getMensaje()           Returns the current record's "mensaje" value
 * @method timestamp           getDesde()             Returns the current record's "desde" value
 * @method timestamp           getHasta()             Returns the current record's "hasta" value
 * @method string              getSufijo()            Returns the current record's "sufijo" value
 * @method string              getUrl()               Returns the current record's "url" value
 * @method integer             getSemilla()           Returns the current record's "semilla" value
 * @method integer             getParticipantesMin()  Returns the current record's "participantes_min" value
 * @method integer             getParticipantesMax()  Returns the current record's "participantes_max" value
 * @method integer             getParticipantesNum()  Returns the current record's "participantes_num" value
 * @method Doctrine_Collection getParticipantes()     Returns the current record's "Participantes" collection
 * @method Doctrine_Collection getCondiciones()       Returns the current record's "Condiciones" collection
 * @method tdhSorteo           setId()                Sets the current record's "id" value
 * @method tdhSorteo           setEstadoVisible()     Sets the current record's "estado_visible" value
 * @method tdhSorteo           setEstadoAbierto()     Sets the current record's "estado_abierto" value
 * @method tdhSorteo           setNombre()            Sets the current record's "nombre" value
 * @method tdhSorteo           setEntradilla()        Sets the current record's "entradilla" value
 * @method tdhSorteo           setAclaraciones()      Sets the current record's "aclaraciones" value
 * @method tdhSorteo           setMensaje()           Sets the current record's "mensaje" value
 * @method tdhSorteo           setDesde()             Sets the current record's "desde" value
 * @method tdhSorteo           setHasta()             Sets the current record's "hasta" value
 * @method tdhSorteo           setSufijo()            Sets the current record's "sufijo" value
 * @method tdhSorteo           setUrl()               Sets the current record's "url" value
 * @method tdhSorteo           setSemilla()           Sets the current record's "semilla" value
 * @method tdhSorteo           setParticipantesMin()  Sets the current record's "participantes_min" value
 * @method tdhSorteo           setParticipantesMax()  Sets the current record's "participantes_max" value
 * @method tdhSorteo           setParticipantesNum()  Sets the current record's "participantes_num" value
 * @method tdhSorteo           setParticipantes()     Sets the current record's "Participantes" collection
 * @method tdhSorteo           setCondiciones()       Sets the current record's "Condiciones" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhSorteo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_sorteo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_visible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('estado_abierto', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('entradilla', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('aclaraciones', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 2000,
             ));
        $this->hasColumn('mensaje', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('desde', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('hasta', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('sufijo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('semilla', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('participantes_min', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '1',
             'length' => 3,
             ));
        $this->hasColumn('participantes_max', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             'length' => 3,
             ));
        $this->hasColumn('participantes_num', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             'length' => 3,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('tdhSorteoParticipante as Participantes', array(
             'local' => 'id',
             'foreign' => 'sorteo_id'));

        $this->hasMany('tdhSorteoCondicion as Condiciones', array(
             'local' => 'id',
             'foreign' => 'sorteo_id'));

        $ehutilesmarkuptohtmlbehavior0 = new ehUtilesMarkupToHtmlBehavior(array(
             'field' => 'descripcion',
             'target' => 'descripcion_html',
             'parsers' => 
             array(
              'html' => false,
              'markdown' => true,
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             'unique' => true,
             ));
        $this->actAs($ehutilesmarkuptohtmlbehavior0);
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}