<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhEnvioSocialPendiente', 'doctrine');

/**
 * BasetdhEnvioSocialPendiente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $programado_para
 * @property enum $servicio
 * @property string $nombre
 * @property string $descripcion
 * @property string $url
 * @property string $imagen
 * @property string $mensaje
 * 
 * @method integer                 getId()              Returns the current record's "id" value
 * @method timestamp               getProgramadoPara()  Returns the current record's "programado_para" value
 * @method enum                    getServicio()        Returns the current record's "servicio" value
 * @method string                  getNombre()          Returns the current record's "nombre" value
 * @method string                  getDescripcion()     Returns the current record's "descripcion" value
 * @method string                  getUrl()             Returns the current record's "url" value
 * @method string                  getImagen()          Returns the current record's "imagen" value
 * @method string                  getMensaje()         Returns the current record's "mensaje" value
 * @method tdhEnvioSocialPendiente setId()              Sets the current record's "id" value
 * @method tdhEnvioSocialPendiente setProgramadoPara()  Sets the current record's "programado_para" value
 * @method tdhEnvioSocialPendiente setServicio()        Sets the current record's "servicio" value
 * @method tdhEnvioSocialPendiente setNombre()          Sets the current record's "nombre" value
 * @method tdhEnvioSocialPendiente setDescripcion()     Sets the current record's "descripcion" value
 * @method tdhEnvioSocialPendiente setUrl()             Sets the current record's "url" value
 * @method tdhEnvioSocialPendiente setImagen()          Sets the current record's "imagen" value
 * @method tdhEnvioSocialPendiente setMensaje()         Sets the current record's "mensaje" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhEnvioSocialPendiente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_envio_social_pendiente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('programado_para', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('servicio', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'facebook',
              1 => 'twitter',
             ),
             'default' => 'twitter',
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('mensaje', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}