<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhSeccion', 'doctrine');

/**
 * BasetdhSeccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $nombre_original
 * @property boolean $estado_activa
 * @property integer $favoritos
 * @property string $url
 * @property integer $genero_id
 * @property string $color_menu
 * @property integer $tipo_id
 * @property integer $editor_id
 * @property integer $tablon_id
 * @property tdhGenero $Genero
 * @property tdhSeccionTipo $Tipo
 * @property tdhEditor $Editor
 * @property ehForoTablon $Tablon
 * @property Doctrine_Collection $FavoritaDeUsuarios
 * @property Doctrine_Collection $HojasDeEstilo
 * @property Doctrine_Collection $tdhSeccionEstilo
 * @property Doctrine_Collection $Noticias
 * @property Doctrine_Collection $Recursos
 * @property Doctrine_Collection $Criticas
 * @property Doctrine_Collection $RegistrosDePopularidad
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method string              getNombreOriginal()         Returns the current record's "nombre_original" value
 * @method boolean             getEstadoActiva()           Returns the current record's "estado_activa" value
 * @method integer             getFavoritos()              Returns the current record's "favoritos" value
 * @method string              getUrl()                    Returns the current record's "url" value
 * @method integer             getGeneroId()               Returns the current record's "genero_id" value
 * @method string              getColorMenu()              Returns the current record's "color_menu" value
 * @method integer             getTipoId()                 Returns the current record's "tipo_id" value
 * @method integer             getEditorId()               Returns the current record's "editor_id" value
 * @method integer             getTablonId()               Returns the current record's "tablon_id" value
 * @method tdhGenero           getGenero()                 Returns the current record's "Genero" value
 * @method tdhSeccionTipo      getTipo()                   Returns the current record's "Tipo" value
 * @method tdhEditor           getEditor()                 Returns the current record's "Editor" value
 * @method ehForoTablon        getTablon()                 Returns the current record's "Tablon" value
 * @method Doctrine_Collection getFavoritaDeUsuarios()     Returns the current record's "FavoritaDeUsuarios" collection
 * @method Doctrine_Collection getHojasDeEstilo()          Returns the current record's "HojasDeEstilo" collection
 * @method Doctrine_Collection getTdhSeccionEstilo()       Returns the current record's "tdhSeccionEstilo" collection
 * @method Doctrine_Collection getNoticias()               Returns the current record's "Noticias" collection
 * @method Doctrine_Collection getRecursos()               Returns the current record's "Recursos" collection
 * @method Doctrine_Collection getCriticas()               Returns the current record's "Criticas" collection
 * @method Doctrine_Collection getRegistrosDePopularidad() Returns the current record's "RegistrosDePopularidad" collection
 * @method tdhSeccion          setId()                     Sets the current record's "id" value
 * @method tdhSeccion          setNombre()                 Sets the current record's "nombre" value
 * @method tdhSeccion          setNombreOriginal()         Sets the current record's "nombre_original" value
 * @method tdhSeccion          setEstadoActiva()           Sets the current record's "estado_activa" value
 * @method tdhSeccion          setFavoritos()              Sets the current record's "favoritos" value
 * @method tdhSeccion          setUrl()                    Sets the current record's "url" value
 * @method tdhSeccion          setGeneroId()               Sets the current record's "genero_id" value
 * @method tdhSeccion          setColorMenu()              Sets the current record's "color_menu" value
 * @method tdhSeccion          setTipoId()                 Sets the current record's "tipo_id" value
 * @method tdhSeccion          setEditorId()               Sets the current record's "editor_id" value
 * @method tdhSeccion          setTablonId()               Sets the current record's "tablon_id" value
 * @method tdhSeccion          setGenero()                 Sets the current record's "Genero" value
 * @method tdhSeccion          setTipo()                   Sets the current record's "Tipo" value
 * @method tdhSeccion          setEditor()                 Sets the current record's "Editor" value
 * @method tdhSeccion          setTablon()                 Sets the current record's "Tablon" value
 * @method tdhSeccion          setFavoritaDeUsuarios()     Sets the current record's "FavoritaDeUsuarios" collection
 * @method tdhSeccion          setHojasDeEstilo()          Sets the current record's "HojasDeEstilo" collection
 * @method tdhSeccion          setTdhSeccionEstilo()       Sets the current record's "tdhSeccionEstilo" collection
 * @method tdhSeccion          setNoticias()               Sets the current record's "Noticias" collection
 * @method tdhSeccion          setRecursos()               Sets the current record's "Recursos" collection
 * @method tdhSeccion          setCriticas()               Sets the current record's "Criticas" collection
 * @method tdhSeccion          setRegistrosDePopularidad() Sets the current record's "RegistrosDePopularidad" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhSeccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_seccion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nombre_original', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('estado_activa', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('favoritos', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('genero_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('color_menu', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 32,
             ));
        $this->hasColumn('tipo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('editor_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('tablon_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tdhGenero as Genero', array(
             'local' => 'genero_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhSeccionTipo as Tipo', array(
             'local' => 'tipo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhEditor as Editor', array(
             'local' => 'editor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehForoTablon as Tablon', array(
             'local' => 'tablon_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ehAuthUser as FavoritaDeUsuarios', array(
             'refClass' => 'tdhSeccionFavorita',
             'local' => 'seccion_id',
             'foreign' => 'usuario_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('tdhHojaDeEstilo as HojasDeEstilo', array(
             'refClass' => 'tdhSeccionEstilo',
             'local' => 'seccion_id',
             'foreign' => 'estilo_id'));

        $this->hasMany('tdhSeccionEstilo', array(
             'local' => 'id',
             'foreign' => 'seccion_id'));

        $this->hasMany('tdhNoticia as Noticias', array(
             'local' => 'id',
             'foreign' => 'seccion_id'));

        $this->hasMany('tdhRecurso as Recursos', array(
             'local' => 'id',
             'foreign' => 'seccion_id'));

        $this->hasMany('tdhCritica as Criticas', array(
             'local' => 'id',
             'foreign' => 'seccion_id'));

        $this->hasMany('tdhPopular as RegistrosDePopularidad', array(
             'local' => 'id',
             'foreign' => 'seccion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             ));
        $ehforomarkuptohtmlbehavior0 = new ehForoMarkupToHtmlBehavior();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($ehforomarkuptohtmlbehavior0);
    }
}