<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhCriticaVideo', 'doctrine');

/**
 * BasetdhCriticaVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $comentario
 * @property enum $medio
 * @property string $url
 * @property integer $critica_id
 * @property tdhCritica $Critica
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method string          getComentario() Returns the current record's "comentario" value
 * @method enum            getMedio()      Returns the current record's "medio" value
 * @method string          getUrl()        Returns the current record's "url" value
 * @method integer         getCriticaId()  Returns the current record's "critica_id" value
 * @method tdhCritica      getCritica()    Returns the current record's "Critica" value
 * @method tdhCriticaVideo setId()         Sets the current record's "id" value
 * @method tdhCriticaVideo setComentario() Sets the current record's "comentario" value
 * @method tdhCriticaVideo setMedio()      Sets the current record's "medio" value
 * @method tdhCriticaVideo setUrl()        Sets the current record's "url" value
 * @method tdhCriticaVideo setCriticaId()  Sets the current record's "critica_id" value
 * @method tdhCriticaVideo setCritica()    Sets the current record's "Critica" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhCriticaVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_critica_video');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('comentario', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('medio', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Youtube',
              1 => 'Dailymotion',
             ),
             'notnull' => true,
             'default' => 'Youtube',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('critica_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tdhCritica as Critica', array(
             'local' => 'critica_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}