<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhSeccionFavorita', 'doctrine');

/**
 * BasetdhSeccionFavorita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $seccion_id
 * 
 * @method integer            getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer            getSeccionId()  Returns the current record's "seccion_id" value
 * @method tdhSeccionFavorita setUsuarioId()  Sets the current record's "usuario_id" value
 * @method tdhSeccionFavorita setSeccionId()  Sets the current record's "seccion_id" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhSeccionFavorita extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_seccion_favorita');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('seccion_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}