<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhSorteoCondicion', 'doctrine');

/**
 * BasetdhSorteoCondicion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $url
 * @property string $propietario
 * @property enum $tipo
 * @property integer $sorteo_id
 * @property tdhSorteo $Sorteo
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method string             getNombre()      Returns the current record's "nombre" value
 * @method string             getUrl()         Returns the current record's "url" value
 * @method string             getPropietario() Returns the current record's "propietario" value
 * @method enum               getTipo()        Returns the current record's "tipo" value
 * @method integer            getSorteoId()    Returns the current record's "sorteo_id" value
 * @method tdhSorteo          getSorteo()      Returns the current record's "Sorteo" value
 * @method tdhSorteoCondicion setId()          Sets the current record's "id" value
 * @method tdhSorteoCondicion setNombre()      Sets the current record's "nombre" value
 * @method tdhSorteoCondicion setUrl()         Sets the current record's "url" value
 * @method tdhSorteoCondicion setPropietario() Sets the current record's "propietario" value
 * @method tdhSorteoCondicion setTipo()        Sets the current record's "tipo" value
 * @method tdhSorteoCondicion setSorteoId()    Sets the current record's "sorteo_id" value
 * @method tdhSorteoCondicion setSorteo()      Sets the current record's "Sorteo" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhSorteoCondicion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_sorteo_condicion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('propietario', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('tipo', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'facebook',
              1 => 'twitter',
             ),
             'default' => 'twitter',
             ));
        $this->hasColumn('sorteo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tdhSorteo as Sorteo', array(
             'local' => 'sorteo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}