<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhConsulta', 'doctrine');

/**
 * BasetdhConsulta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo
 * @property string $nombre
 * @property string $descripcion
 * @property string $email
 * @property string $ip
 * @property boolean $resuelto
 * @property integer $usuario_id
 * @property integer $tipo_id
 * @property ehAuthUser $Usuario
 * @property tdhConsultaTipo $Tipo
 * @property Doctrine_Collection $Respuestas
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getCodigo()      Returns the current record's "codigo" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method string              getEmail()       Returns the current record's "email" value
 * @method string              getIp()          Returns the current record's "ip" value
 * @method boolean             getResuelto()    Returns the current record's "resuelto" value
 * @method integer             getUsuarioId()   Returns the current record's "usuario_id" value
 * @method integer             getTipoId()      Returns the current record's "tipo_id" value
 * @method ehAuthUser          getUsuario()     Returns the current record's "Usuario" value
 * @method tdhConsultaTipo     getTipo()        Returns the current record's "Tipo" value
 * @method Doctrine_Collection getRespuestas()  Returns the current record's "Respuestas" collection
 * @method tdhConsulta         setId()          Sets the current record's "id" value
 * @method tdhConsulta         setCodigo()      Sets the current record's "codigo" value
 * @method tdhConsulta         setNombre()      Sets the current record's "nombre" value
 * @method tdhConsulta         setDescripcion() Sets the current record's "descripcion" value
 * @method tdhConsulta         setEmail()       Sets the current record's "email" value
 * @method tdhConsulta         setIp()          Sets the current record's "ip" value
 * @method tdhConsulta         setResuelto()    Sets the current record's "resuelto" value
 * @method tdhConsulta         setUsuarioId()   Sets the current record's "usuario_id" value
 * @method tdhConsulta         setTipoId()      Sets the current record's "tipo_id" value
 * @method tdhConsulta         setUsuario()     Sets the current record's "Usuario" value
 * @method tdhConsulta         setTipo()        Sets the current record's "Tipo" value
 * @method tdhConsulta         setRespuestas()  Sets the current record's "Respuestas" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhConsulta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_consulta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 80,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 4000,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '127.0.0.1',
             'length' => 255,
             ));
        $this->hasColumn('resuelto', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhConsultaTipo as Tipo', array(
             'local' => 'tipo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('tdhConsultaRespuesta as Respuestas', array(
             'local' => 'id',
             'foreign' => 'consulta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}