<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhCriticaCaptura', 'doctrine');

/**
 * BasetdhCriticaCaptura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $comentario
 * @property string $fichero
 * @property boolean $tam_peq
 * @property boolean $tam_med
 * @property boolean $tam_gra
 * @property integer $critica_id
 * @property tdhCritica $Critica
 * 
 * @method integer           getId()         Returns the current record's "id" value
 * @method string            getComentario() Returns the current record's "comentario" value
 * @method string            getFichero()    Returns the current record's "fichero" value
 * @method boolean           getTamPeq()     Returns the current record's "tam_peq" value
 * @method boolean           getTamMed()     Returns the current record's "tam_med" value
 * @method boolean           getTamGra()     Returns the current record's "tam_gra" value
 * @method integer           getCriticaId()  Returns the current record's "critica_id" value
 * @method tdhCritica        getCritica()    Returns the current record's "Critica" value
 * @method tdhCriticaCaptura setId()         Sets the current record's "id" value
 * @method tdhCriticaCaptura setComentario() Sets the current record's "comentario" value
 * @method tdhCriticaCaptura setFichero()    Sets the current record's "fichero" value
 * @method tdhCriticaCaptura setTamPeq()     Sets the current record's "tam_peq" value
 * @method tdhCriticaCaptura setTamMed()     Sets the current record's "tam_med" value
 * @method tdhCriticaCaptura setTamGra()     Sets the current record's "tam_gra" value
 * @method tdhCriticaCaptura setCriticaId()  Sets the current record's "critica_id" value
 * @method tdhCriticaCaptura setCritica()    Sets the current record's "Critica" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhCriticaCaptura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_critica_captura');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('comentario', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('fichero', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('tam_peq', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('tam_med', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('tam_gra', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('critica_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tdhCritica as Critica', array(
             'local' => 'critica_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}