<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhPerfil', 'doctrine');

/**
 * BasetdhPerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhPerfil extends ehForoPerfil
{
    public function setUp()
    {
        parent::setUp();
        
    }
}