<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhAsociacionTipo', 'doctrine');

/**
 * BasetdhAsociacionTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Asociaciones
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method Doctrine_Collection getAsociaciones() Returns the current record's "Asociaciones" collection
 * @method tdhAsociacionTipo   setId()           Sets the current record's "id" value
 * @method tdhAsociacionTipo   setNombre()       Sets the current record's "nombre" value
 * @method tdhAsociacionTipo   setAsociaciones() Sets the current record's "Asociaciones" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhAsociacionTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_asociacion_tipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('tdhAsociacion as Asociaciones', array(
             'local' => 'id',
             'foreign' => 'tipo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}