<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhEventoApuntado', 'doctrine');

/**
 * BasetdhEventoApuntado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $evento_id
 * 
 * @method integer           getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer           getEventoId()   Returns the current record's "evento_id" value
 * @method tdhEventoApuntado setUsuarioId()  Sets the current record's "usuario_id" value
 * @method tdhEventoApuntado setEventoId()   Sets the current record's "evento_id" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhEventoApuntado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_evento_apuntado');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('evento_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}