<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhConsultaTipo', 'doctrine');

/**
 * BasetdhConsultaTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Consultores
 * @property Doctrine_Collection $Consultas
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method Doctrine_Collection getConsultores() Returns the current record's "Consultores" collection
 * @method Doctrine_Collection getConsultas()   Returns the current record's "Consultas" collection
 * @method tdhConsultaTipo     setId()          Sets the current record's "id" value
 * @method tdhConsultaTipo     setNombre()      Sets the current record's "nombre" value
 * @method tdhConsultaTipo     setConsultores() Sets the current record's "Consultores" collection
 * @method tdhConsultaTipo     setConsultas()   Sets the current record's "Consultas" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhConsultaTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_consulta_tipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ehAuthUser as Consultores', array(
             'refClass' => 'tdhConsultaTipoUsuario',
             'local' => 'tipo_id',
             'foreign' => 'usuario_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('tdhConsulta as Consultas', array(
             'local' => 'id',
             'foreign' => 'tipo_id'));
    }
}