<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhHojaDeEstilo', 'doctrine');

/**
 * BasetdhHojaDeEstilo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $filename
 * @property string $media
 * @property string $content
 * @property Doctrine_Collection $Secciones
 * @property Doctrine_Collection $tdhSeccionEstilo
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getTitle()            Returns the current record's "title" value
 * @method string              getFilename()         Returns the current record's "filename" value
 * @method string              getMedia()            Returns the current record's "media" value
 * @method string              getContent()          Returns the current record's "content" value
 * @method Doctrine_Collection getSecciones()        Returns the current record's "Secciones" collection
 * @method Doctrine_Collection getTdhSeccionEstilo() Returns the current record's "tdhSeccionEstilo" collection
 * @method tdhHojaDeEstilo     setId()               Sets the current record's "id" value
 * @method tdhHojaDeEstilo     setTitle()            Sets the current record's "title" value
 * @method tdhHojaDeEstilo     setFilename()         Sets the current record's "filename" value
 * @method tdhHojaDeEstilo     setMedia()            Sets the current record's "media" value
 * @method tdhHojaDeEstilo     setContent()          Sets the current record's "content" value
 * @method tdhHojaDeEstilo     setSecciones()        Sets the current record's "Secciones" collection
 * @method tdhHojaDeEstilo     setTdhSeccionEstilo() Sets the current record's "tdhSeccionEstilo" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhHojaDeEstilo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_hoja_de_estilo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('media', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'all',
             'length' => 10,
             ));
        $this->hasColumn('content', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('tdhSeccion as Secciones', array(
             'refClass' => 'tdhSeccionEstilo',
             'local' => 'estilo_id',
             'foreign' => 'seccion_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('tdhSeccionEstilo', array(
             'local' => 'id',
             'foreign' => 'estilo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}