<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhNoticia', 'doctrine');

/**
 * BasetdhNoticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $estado_aprobado
 * @property boolean $es_destacada
 * @property string $entradilla
 * @property string $nombre_fuente
 * @property string $url_fuente
 * @property integer $seccion_id
 * @property integer $hilo_id
 * @property ehForoHilo $Hilo
 * @property tdhSeccion $Seccion
 * 
 * @method integer    getId()              Returns the current record's "id" value
 * @method boolean    getEstadoAprobado()  Returns the current record's "estado_aprobado" value
 * @method boolean    getEsDestacada()     Returns the current record's "es_destacada" value
 * @method string     getEntradilla()      Returns the current record's "entradilla" value
 * @method string     getNombreFuente()    Returns the current record's "nombre_fuente" value
 * @method string     getUrlFuente()       Returns the current record's "url_fuente" value
 * @method integer    getSeccionId()       Returns the current record's "seccion_id" value
 * @method integer    getHiloId()          Returns the current record's "hilo_id" value
 * @method ehForoHilo getHilo()            Returns the current record's "Hilo" value
 * @method tdhSeccion getSeccion()         Returns the current record's "Seccion" value
 * @method tdhNoticia setId()              Sets the current record's "id" value
 * @method tdhNoticia setEstadoAprobado()  Sets the current record's "estado_aprobado" value
 * @method tdhNoticia setEsDestacada()     Sets the current record's "es_destacada" value
 * @method tdhNoticia setEntradilla()      Sets the current record's "entradilla" value
 * @method tdhNoticia setNombreFuente()    Sets the current record's "nombre_fuente" value
 * @method tdhNoticia setUrlFuente()       Sets the current record's "url_fuente" value
 * @method tdhNoticia setSeccionId()       Sets the current record's "seccion_id" value
 * @method tdhNoticia setHiloId()          Sets the current record's "hilo_id" value
 * @method tdhNoticia setHilo()            Sets the current record's "Hilo" value
 * @method tdhNoticia setSeccion()         Sets the current record's "Seccion" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhNoticia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_noticia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_aprobado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('es_destacada', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('entradilla', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('nombre_fuente', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('url_fuente', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('seccion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('hilo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehForoHilo as Hilo', array(
             'local' => 'hilo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tdhSeccion as Seccion', array(
             'local' => 'seccion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}