<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhEditor', 'doctrine');

/**
 * BasetdhEditor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $web
 * @property Doctrine_Collection $Secciones
 * @property Doctrine_Collection $Criticas
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method string              getWeb()       Returns the current record's "web" value
 * @method Doctrine_Collection getSecciones() Returns the current record's "Secciones" collection
 * @method Doctrine_Collection getCriticas()  Returns the current record's "Criticas" collection
 * @method tdhEditor           setId()        Sets the current record's "id" value
 * @method tdhEditor           setNombre()    Sets the current record's "nombre" value
 * @method tdhEditor           setWeb()       Sets the current record's "web" value
 * @method tdhEditor           setSecciones() Sets the current record's "Secciones" collection
 * @method tdhEditor           setCriticas()  Sets the current record's "Criticas" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhEditor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_editor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('web', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('tdhSeccion as Secciones', array(
             'local' => 'id',
             'foreign' => 'editor_id'));

        $this->hasMany('tdhCritica as Criticas', array(
             'local' => 'id',
             'foreign' => 'editor_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}