<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhLicencia', 'doctrine');

/**
 * BasetdhLicencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $url
 * @property Doctrine_Collection $Recursos
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method string              getUrl()         Returns the current record's "url" value
 * @method Doctrine_Collection getRecursos()    Returns the current record's "Recursos" collection
 * @method tdhLicencia         setId()          Sets the current record's "id" value
 * @method tdhLicencia         setNombre()      Sets the current record's "nombre" value
 * @method tdhLicencia         setDescripcion() Sets the current record's "descripcion" value
 * @method tdhLicencia         setUrl()         Sets the current record's "url" value
 * @method tdhLicencia         setRecursos()    Sets the current record's "Recursos" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhLicencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_licencia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('tdhRecurso as Recursos', array(
             'local' => 'id',
             'foreign' => 'licencia_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}