<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhRecursoTipo', 'doctrine');

/**
 * BasetdhRecursoTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Recursos
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getRecursos()    Returns the current record's "Recursos" collection
 * @method tdhRecursoTipo      setId()          Sets the current record's "id" value
 * @method tdhRecursoTipo      setNombre()      Sets the current record's "nombre" value
 * @method tdhRecursoTipo      setDescripcion() Sets the current record's "descripcion" value
 * @method tdhRecursoTipo      setRecursos()    Sets the current record's "Recursos" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhRecursoTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_recurso_tipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('tdhRecurso as Recursos', array(
             'local' => 'id',
             'foreign' => 'tipo_id'));
    }
}