<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhCriticaNota', 'doctrine');

/**
 * BasetdhCriticaNota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property integer $critica_id
 * @property float $nota
 * @property tdhCritica $Critica
 * @property ehAuthUser $Usuario
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer        getCriticaId()  Returns the current record's "critica_id" value
 * @method float          getNota()       Returns the current record's "nota" value
 * @method tdhCritica     getCritica()    Returns the current record's "Critica" value
 * @method ehAuthUser     getUsuario()    Returns the current record's "Usuario" value
 * @method tdhCriticaNota setId()         Sets the current record's "id" value
 * @method tdhCriticaNota setUsuarioId()  Sets the current record's "usuario_id" value
 * @method tdhCriticaNota setCriticaId()  Sets the current record's "critica_id" value
 * @method tdhCriticaNota setNota()       Sets the current record's "nota" value
 * @method tdhCriticaNota setCritica()    Sets the current record's "Critica" value
 * @method tdhCriticaNota setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhCriticaNota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_critica_nota');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('critica_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('nota', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tdhCritica as Critica', array(
             'local' => 'critica_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}