<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tdhAnuncioPago', 'doctrine');

/**
 * BasetdhAnuncioPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property float $cantidad
 * @property integer $usuario_id
 * @property integer $anuncio_id
 * @property tdhAnuncio $Anuncio
 * @property ehAuthUser $Usuario
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method float          getCantidad()   Returns the current record's "cantidad" value
 * @method integer        getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer        getAnuncioId()  Returns the current record's "anuncio_id" value
 * @method tdhAnuncio     getAnuncio()    Returns the current record's "Anuncio" value
 * @method ehAuthUser     getUsuario()    Returns the current record's "Usuario" value
 * @method tdhAnuncioPago setId()         Sets the current record's "id" value
 * @method tdhAnuncioPago setCantidad()   Sets the current record's "cantidad" value
 * @method tdhAnuncioPago setUsuarioId()  Sets the current record's "usuario_id" value
 * @method tdhAnuncioPago setAnuncioId()  Sets the current record's "anuncio_id" value
 * @method tdhAnuncioPago setAnuncio()    Sets the current record's "Anuncio" value
 * @method tdhAnuncioPago setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetdhAnuncioPago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tdh_anuncio_pago');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('anuncio_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tdhAnuncio as Anuncio', array(
             'local' => 'anuncio_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}