<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ehForoHilo extends PluginehForoHilo
{
  public function getPagerComentarios($pagina = 1, $opciones = array())
  {
    $pager = new sfDoctrinePager('ehForoMensaje', 15);
    $pager->setTableMethod('autorizados');
    $pager->setPage($pagina);
    
    $pager->getQuery()
      ->addWhere('m.hilo_id = ?', $this->getId())
      ->addWhere('m.id != ?', $this->getPrimerMensaje()->getId())
      ->orderBy('m.created_at DESC');
    
    $pager->init();
    
    return $pager;
  }
  
  public function getRouting()
  {
    if(isset($this->Recurso))
    {
      return '@tdh_recurso?id='.$this->getRecurso()->getId().'&slug='.$this->getPrimerMensaje()->getSlug();
    }
    elseif(isset($this->Critica))
    {
      return '@tdh_critica?id='.$this->getCritica()->getId().'&slug='.$this->getPrimerMensaje()->getSlug();
    }
    elseif(isset($this->Evento))
    {
      return '@tdh_evento?id='.$this->getEvento()->getId().'&slug='.$this->getPrimerMensaje()->getSlug();
    }
    elseif(isset($this->Noticia))
    {
      return '@tdh_noticia?id='.$this->getNoticia()->getId().'&slug='.$this->getPrimerMensaje()->getSlug();
    }
    else
    {
      return '@eh_foro_tema?id='.$this->getId().'&pagina=1';
    }
  }
  
  protected function getClassContenidoPreferente($withGet = true)
  {
    if(isset($this->Recurso))
    {
      return $withGet ? 'getRecurso' : 'Recurso';
    }
    elseif(isset($this->Critica))
    {
      return $withGet ? 'getCritica' : 'Critica';
    }
    elseif(isset($this->Evento))
    {
      return $withGet ? 'getEvento' : 'Evento';
    }
    elseif(isset($this->Noticia))
    {
      return $withGet ? 'getNoticia' : 'Noticia';
    }
    else
    {
      return '';
    }
  } 
  
  public function getContenidoImagePath($size = 'med', $defecto = true)
  {
    if($classPreferente = $this->getClassContenidoPreferente())
    {
      return $this->$classPreferente()->getImagePath($size, $defecto);
    }
    else
    {
      return '';
    }
  }
  
  public function hasContenidoImage($size = 'med')
  {
    if($classPreferente = $this->getClassContenidoPreferente())
    {
      return $this->$classPreferente()->hasImage($size);
    }
    else
    {
      return false;
    }
  }
}