<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ehForoMensaje extends PluginehForoMensaje
{
  protected $paginadorContenido = null;
  
  public function getPaginadorContenido()
  {
    if(is_null($this->paginadorContenido))
    {
      $this->paginadorContenido = new tdhPaginadorContenido($this->getCuerpoHtml());
    }
    
    return $this->paginadorContenido;
  }
  
  public function getCuerpoHtmlDividido($pagina = 1, $divisor = '</p>', $parrafosPorPagina = 7)
  {
    return $this->getPaginadorContenido()->setPagina($pagina)->getCuerpoHtmlActual();
  }
  
  public function preInsert($event)
  {
    if($this->getVisibleDesde() && date('H:i', strtotime($this->getVisibleDesde())) == '00:00')
    {
      sfContext::getInstance()->getLogger()->notice('Hora visible desde:'. date('Y-m-d H:i:s', strtotime($this->getVisibleDesde())));
      $this->setVisibleDesde(date('Y-m-d H:i:s', (strtotime($this->getVisibleDesde()) + sfConfig::get('app_seg_visible_desde', 12*60*60))));
    }
    
    parent::preInsert($event);
  }
}