<?php

/**
 * ehForoAmigoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ehForoAmigoTable extends PluginehForoAmigoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ehForoAmigoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ehForoAmigo');
    }
}