<?php

/**
 * ehForoHiloSeguimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ehForoHiloSeguimientoTable extends PluginehForoHiloSeguimientoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ehForoHiloSeguimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ehForoHiloSeguimiento');
    }
}