<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ehForoSeccion extends PluginehForoSeccion
{
  public function __toString()
  {
    return $this->getNombre();
  }
}