<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoLeidoHilo', 'doctrine');

/**
 * BaseehForoLeidoHilo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $hilo_id
 * @property timestamp $read_at
 * @property ehAuthUser $Usuario
 * @property ehForoHilo $Hilo
 * 
 * @method integer         getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer         getHiloId()     Returns the current record's "hilo_id" value
 * @method timestamp       getReadAt()     Returns the current record's "read_at" value
 * @method ehAuthUser      getUsuario()    Returns the current record's "Usuario" value
 * @method ehForoHilo      getHilo()       Returns the current record's "Hilo" value
 * @method ehForoLeidoHilo setUsuarioId()  Sets the current record's "usuario_id" value
 * @method ehForoLeidoHilo setHiloId()     Sets the current record's "hilo_id" value
 * @method ehForoLeidoHilo setReadAt()     Sets the current record's "read_at" value
 * @method ehForoLeidoHilo setUsuario()    Sets the current record's "Usuario" value
 * @method ehForoLeidoHilo setHilo()       Sets the current record's "Hilo" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoLeidoHilo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_leido_hilo');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('hilo_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('read_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehForoHilo as Hilo', array(
             'local' => 'hilo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}