<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoGrupo', 'doctrine');

/**
 * BaseehForoGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property boolean $es_restringido
 * @property Doctrine_Collection $Usuarios
 * @property Doctrine_Collection $Tablones
 * @property Doctrine_Collection $ehForoGrupoUsuario
 * @property Doctrine_Collection $ehForoStaffTablon
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getNombre()             Returns the current record's "nombre" value
 * @method boolean             getEsRestringido()      Returns the current record's "es_restringido" value
 * @method Doctrine_Collection getUsuarios()           Returns the current record's "Usuarios" collection
 * @method Doctrine_Collection getTablones()           Returns the current record's "Tablones" collection
 * @method Doctrine_Collection getEhForoGrupoUsuario() Returns the current record's "ehForoGrupoUsuario" collection
 * @method Doctrine_Collection getEhForoStaffTablon()  Returns the current record's "ehForoStaffTablon" collection
 * @method ehForoGrupo         setId()                 Sets the current record's "id" value
 * @method ehForoGrupo         setNombre()             Sets the current record's "nombre" value
 * @method ehForoGrupo         setEsRestringido()      Sets the current record's "es_restringido" value
 * @method ehForoGrupo         setUsuarios()           Sets the current record's "Usuarios" collection
 * @method ehForoGrupo         setTablones()           Sets the current record's "Tablones" collection
 * @method ehForoGrupo         setEhForoGrupoUsuario() Sets the current record's "ehForoGrupoUsuario" collection
 * @method ehForoGrupo         setEhForoStaffTablon()  Sets the current record's "ehForoStaffTablon" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_grupo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('es_restringido', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ehAuthUser as Usuarios', array(
             'refClass' => 'ehForoGrupoUsuario',
             'local' => 'grupo_id',
             'foreign' => 'usuario_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ehForoTablon as Tablones', array(
             'refClass' => 'ehForoStaffTablon',
             'local' => 'grupo_id',
             'foreign' => 'tablon_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ehForoGrupoUsuario', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));

        $this->hasMany('ehForoStaffTablon', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             'unique' => true,
             ));
        $ehforomarkuptohtmlbehavior0 = new ehForoMarkupToHtmlBehavior();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($ehforomarkuptohtmlbehavior0);
        $this->actAs($timestampable0);
    }
}