<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoHiloSeguimiento', 'doctrine');

/**
 * BaseehForoHiloSeguimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $es_persistente
 * @property integer $hilo_id
 * @property integer $usuario_id
 * @property ehAuthUser $Usuario
 * @property ehForoHilo $Hilo
 * 
 * @method integer               getId()             Returns the current record's "id" value
 * @method boolean               getEsPersistente()  Returns the current record's "es_persistente" value
 * @method integer               getHiloId()         Returns the current record's "hilo_id" value
 * @method integer               getUsuarioId()      Returns the current record's "usuario_id" value
 * @method ehAuthUser            getUsuario()        Returns the current record's "Usuario" value
 * @method ehForoHilo            getHilo()           Returns the current record's "Hilo" value
 * @method ehForoHiloSeguimiento setId()             Sets the current record's "id" value
 * @method ehForoHiloSeguimiento setEsPersistente()  Sets the current record's "es_persistente" value
 * @method ehForoHiloSeguimiento setHiloId()         Sets the current record's "hilo_id" value
 * @method ehForoHiloSeguimiento setUsuarioId()      Sets the current record's "usuario_id" value
 * @method ehForoHiloSeguimiento setUsuario()        Sets the current record's "Usuario" value
 * @method ehForoHiloSeguimiento setHilo()           Sets the current record's "Hilo" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoHiloSeguimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_hilo_seguimiento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('es_persistente', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('hilo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehForoHilo as Hilo', array(
             'local' => 'hilo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}