<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoKarma', 'doctrine');

/**
 * BaseehForoKarma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mensaje_id
 * @property integer $usuario_id
 * @property integer $puntos
 * @property ehForoMensaje $Mensaje
 * @property ehAuthUser $Usuario
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getMensajeId()  Returns the current record's "mensaje_id" value
 * @method integer       getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer       getPuntos()     Returns the current record's "puntos" value
 * @method ehForoMensaje getMensaje()    Returns the current record's "Mensaje" value
 * @method ehAuthUser    getUsuario()    Returns the current record's "Usuario" value
 * @method ehForoKarma   setId()         Sets the current record's "id" value
 * @method ehForoKarma   setMensajeId()  Sets the current record's "mensaje_id" value
 * @method ehForoKarma   setUsuarioId()  Sets the current record's "usuario_id" value
 * @method ehForoKarma   setPuntos()     Sets the current record's "puntos" value
 * @method ehForoKarma   setMensaje()    Sets the current record's "Mensaje" value
 * @method ehForoKarma   setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoKarma extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_karma');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mensaje_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('puntos', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehForoMensaje as Mensaje', array(
             'local' => 'mensaje_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}