<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoGrupoUsuario', 'doctrine');

/**
 * BaseehForoGrupoUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $grupo_id
 * @property integer $usuario_id
 * @property ehForoGrupo $Grupo
 * @property ehAuthUser $Usuario
 * 
 * @method integer            getGrupoId()    Returns the current record's "grupo_id" value
 * @method integer            getUsuarioId()  Returns the current record's "usuario_id" value
 * @method ehForoGrupo        getGrupo()      Returns the current record's "Grupo" value
 * @method ehAuthUser         getUsuario()    Returns the current record's "Usuario" value
 * @method ehForoGrupoUsuario setGrupoId()    Sets the current record's "grupo_id" value
 * @method ehForoGrupoUsuario setUsuarioId()  Sets the current record's "usuario_id" value
 * @method ehForoGrupoUsuario setGrupo()      Sets the current record's "Grupo" value
 * @method ehForoGrupoUsuario setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoGrupoUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_grupo_usuario');
        $this->hasColumn('grupo_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehForoGrupo as Grupo', array(
             'local' => 'grupo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehAuthUser as Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}