<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoHilo', 'doctrine');

/**
 * BaseehForoHilo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $estado_oculto
 * @property boolean $estado_cerrado
 * @property boolean $estado_staff
 * @property boolean $estado_pinchado
 * @property boolean $estado_general
 * @property boolean $estado_seccion
 * @property integer $leido
 * @property integer $respuestas
 * @property integer $tablon_id
 * @property integer $primer_mensaje_id
 * @property integer $ultimo_mensaje_id
 * @property ehForoTablon $Tablon
 * @property ehForoMensaje $PrimerMensaje
 * @property ehForoMensaje $UltimoMensaje
 * @property Doctrine_Collection $Mensajes
 * @property Doctrine_Collection $Leidos
 * @property Doctrine_Collection $Seguimientos
 * @property tdhEvento $Evento
 * @property tdhArticulo $Articulo
 * @property tdhNoticia $Noticia
 * @property tdhRecurso $Recurso
 * @property Doctrine_Collection $Donaciones
 * @property tdhCritica $Critica
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method boolean             getEstadoOculto()      Returns the current record's "estado_oculto" value
 * @method boolean             getEstadoCerrado()     Returns the current record's "estado_cerrado" value
 * @method boolean             getEstadoStaff()       Returns the current record's "estado_staff" value
 * @method boolean             getEstadoPinchado()    Returns the current record's "estado_pinchado" value
 * @method boolean             getEstadoGeneral()     Returns the current record's "estado_general" value
 * @method boolean             getEstadoSeccion()     Returns the current record's "estado_seccion" value
 * @method integer             getLeido()             Returns the current record's "leido" value
 * @method integer             getRespuestas()        Returns the current record's "respuestas" value
 * @method integer             getTablonId()          Returns the current record's "tablon_id" value
 * @method integer             getPrimerMensajeId()   Returns the current record's "primer_mensaje_id" value
 * @method integer             getUltimoMensajeId()   Returns the current record's "ultimo_mensaje_id" value
 * @method ehForoTablon        getTablon()            Returns the current record's "Tablon" value
 * @method ehForoMensaje       getPrimerMensaje()     Returns the current record's "PrimerMensaje" value
 * @method ehForoMensaje       getUltimoMensaje()     Returns the current record's "UltimoMensaje" value
 * @method Doctrine_Collection getMensajes()          Returns the current record's "Mensajes" collection
 * @method Doctrine_Collection getLeidos()            Returns the current record's "Leidos" collection
 * @method Doctrine_Collection getSeguimientos()      Returns the current record's "Seguimientos" collection
 * @method tdhEvento           getEvento()            Returns the current record's "Evento" value
 * @method tdhArticulo         getArticulo()          Returns the current record's "Articulo" value
 * @method tdhNoticia          getNoticia()           Returns the current record's "Noticia" value
 * @method tdhRecurso          getRecurso()           Returns the current record's "Recurso" value
 * @method Doctrine_Collection getDonaciones()        Returns the current record's "Donaciones" collection
 * @method tdhCritica          getCritica()           Returns the current record's "Critica" value
 * @method ehForoHilo          setId()                Sets the current record's "id" value
 * @method ehForoHilo          setEstadoOculto()      Sets the current record's "estado_oculto" value
 * @method ehForoHilo          setEstadoCerrado()     Sets the current record's "estado_cerrado" value
 * @method ehForoHilo          setEstadoStaff()       Sets the current record's "estado_staff" value
 * @method ehForoHilo          setEstadoPinchado()    Sets the current record's "estado_pinchado" value
 * @method ehForoHilo          setEstadoGeneral()     Sets the current record's "estado_general" value
 * @method ehForoHilo          setEstadoSeccion()     Sets the current record's "estado_seccion" value
 * @method ehForoHilo          setLeido()             Sets the current record's "leido" value
 * @method ehForoHilo          setRespuestas()        Sets the current record's "respuestas" value
 * @method ehForoHilo          setTablonId()          Sets the current record's "tablon_id" value
 * @method ehForoHilo          setPrimerMensajeId()   Sets the current record's "primer_mensaje_id" value
 * @method ehForoHilo          setUltimoMensajeId()   Sets the current record's "ultimo_mensaje_id" value
 * @method ehForoHilo          setTablon()            Sets the current record's "Tablon" value
 * @method ehForoHilo          setPrimerMensaje()     Sets the current record's "PrimerMensaje" value
 * @method ehForoHilo          setUltimoMensaje()     Sets the current record's "UltimoMensaje" value
 * @method ehForoHilo          setMensajes()          Sets the current record's "Mensajes" collection
 * @method ehForoHilo          setLeidos()            Sets the current record's "Leidos" collection
 * @method ehForoHilo          setSeguimientos()      Sets the current record's "Seguimientos" collection
 * @method ehForoHilo          setEvento()            Sets the current record's "Evento" value
 * @method ehForoHilo          setArticulo()          Sets the current record's "Articulo" value
 * @method ehForoHilo          setNoticia()           Sets the current record's "Noticia" value
 * @method ehForoHilo          setRecurso()           Sets the current record's "Recurso" value
 * @method ehForoHilo          setDonaciones()        Sets the current record's "Donaciones" collection
 * @method ehForoHilo          setCritica()           Sets the current record's "Critica" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoHilo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_hilo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_oculto', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_cerrado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_staff', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_pinchado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_general', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_seccion', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('leido', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('respuestas', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('tablon_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('primer_mensaje_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('ultimo_mensaje_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehForoTablon as Tablon', array(
             'local' => 'tablon_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehForoMensaje as PrimerMensaje', array(
             'local' => 'primer_mensaje_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('ehForoMensaje as UltimoMensaje', array(
             'local' => 'ultimo_mensaje_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('ehForoMensaje as Mensajes', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));

        $this->hasMany('ehForoLeidoHilo as Leidos', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));

        $this->hasMany('ehForoHiloSeguimiento as Seguimientos', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));

        $this->hasOne('tdhEvento as Evento', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));

        $this->hasOne('tdhArticulo as Articulo', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));

        $this->hasOne('tdhNoticia as Noticia', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));

        $this->hasOne('tdhRecurso as Recurso', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));

        $this->hasMany('tdhDonacion as Donaciones', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));

        $this->hasOne('tdhCritica as Critica', array(
             'local' => 'id',
             'foreign' => 'hilo_id'));
    }
}