<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoMensajePrivado', 'doctrine');

/**
 * BaseehForoMensajePrivado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $estado_leido
 * @property boolean $estado_borrado_procedencia
 * @property boolean $estado_borrado_destino
 * @property boolean $estado_notificacion
 * @property integer $mensaje_id
 * @property integer $usuario_destino_id
 * @property ehForoMensaje $Mensaje
 * @property ehAuthUser $Destinatario
 * 
 * @method integer              getId()                         Returns the current record's "id" value
 * @method boolean              getEstadoLeido()                Returns the current record's "estado_leido" value
 * @method boolean              getEstadoBorradoProcedencia()   Returns the current record's "estado_borrado_procedencia" value
 * @method boolean              getEstadoBorradoDestino()       Returns the current record's "estado_borrado_destino" value
 * @method boolean              getEstadoNotificacion()         Returns the current record's "estado_notificacion" value
 * @method integer              getMensajeId()                  Returns the current record's "mensaje_id" value
 * @method integer              getUsuarioDestinoId()           Returns the current record's "usuario_destino_id" value
 * @method ehForoMensaje        getMensaje()                    Returns the current record's "Mensaje" value
 * @method ehAuthUser           getDestinatario()               Returns the current record's "Destinatario" value
 * @method ehForoMensajePrivado setId()                         Sets the current record's "id" value
 * @method ehForoMensajePrivado setEstadoLeido()                Sets the current record's "estado_leido" value
 * @method ehForoMensajePrivado setEstadoBorradoProcedencia()   Sets the current record's "estado_borrado_procedencia" value
 * @method ehForoMensajePrivado setEstadoBorradoDestino()       Sets the current record's "estado_borrado_destino" value
 * @method ehForoMensajePrivado setEstadoNotificacion()         Sets the current record's "estado_notificacion" value
 * @method ehForoMensajePrivado setMensajeId()                  Sets the current record's "mensaje_id" value
 * @method ehForoMensajePrivado setUsuarioDestinoId()           Sets the current record's "usuario_destino_id" value
 * @method ehForoMensajePrivado setMensaje()                    Sets the current record's "Mensaje" value
 * @method ehForoMensajePrivado setDestinatario()               Sets the current record's "Destinatario" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoMensajePrivado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_mensaje_privado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_leido', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_borrado_procedencia', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_borrado_destino', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_notificacion', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('mensaje_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('usuario_destino_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehForoMensaje as Mensaje', array(
             'local' => 'mensaje_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehAuthUser as Destinatario', array(
             'local' => 'usuario_destino_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}