<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoSeccion', 'doctrine');

/**
 * BaseehForoSeccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $estado_oculto
 * @property integer $ordinal
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Tablones
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method boolean             getEstadoOculto()  Returns the current record's "estado_oculto" value
 * @method integer             getOrdinal()       Returns the current record's "ordinal" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTablones()      Returns the current record's "Tablones" collection
 * @method ehForoSeccion       setId()            Sets the current record's "id" value
 * @method ehForoSeccion       setEstadoOculto()  Sets the current record's "estado_oculto" value
 * @method ehForoSeccion       setOrdinal()       Sets the current record's "ordinal" value
 * @method ehForoSeccion       setNombre()        Sets the current record's "nombre" value
 * @method ehForoSeccion       setDescripcion()   Sets the current record's "descripcion" value
 * @method ehForoSeccion       setTablones()      Sets the current record's "Tablones" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoSeccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_seccion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_oculto', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('ordinal', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ehForoTablon as Tablones', array(
             'local' => 'id',
             'foreign' => 'seccion_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}