<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoAdjuntoTipo', 'doctrine');

/**
 * BaseehForoAdjuntoTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $url
 * @property string $dir
 * @property Doctrine_Collection $Adjuntos
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method string              getUrl()      Returns the current record's "url" value
 * @method string              getDir()      Returns the current record's "dir" value
 * @method Doctrine_Collection getAdjuntos() Returns the current record's "Adjuntos" collection
 * @method ehForoAdjuntoTipo   setId()       Sets the current record's "id" value
 * @method ehForoAdjuntoTipo   setNombre()   Sets the current record's "nombre" value
 * @method ehForoAdjuntoTipo   setUrl()      Sets the current record's "url" value
 * @method ehForoAdjuntoTipo   setDir()      Sets the current record's "dir" value
 * @method ehForoAdjuntoTipo   setAdjuntos() Sets the current record's "Adjuntos" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoAdjuntoTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_adjunto_tipo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('dir', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ehForoAdjunto as Adjuntos', array(
             'local' => 'id',
             'foreign' => 'tipo_id'));
    }
}