<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoVisible', 'doctrine');

/**
 * BaseehForoVisible
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $foro_id
 * 
 * @method integer       getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer       getForoId()     Returns the current record's "foro_id" value
 * @method ehForoVisible setUsuarioId()  Sets the current record's "usuario_id" value
 * @method ehForoVisible setForoId()     Sets the current record's "foro_id" value
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoVisible extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_visible');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('foro_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}