<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehForoTablon', 'doctrine');

/**
 * BaseehForoTablon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $estado_oculto
 * @property boolean $estado_restringido_hilos
 * @property boolean $estado_restringido_respuestas
 * @property integer $ordinal
 * @property string $nombre
 * @property string $descripcion
 * @property integer $num_subtablones
 * @property integer $num_hilos
 * @property integer $num_mensajes
 * @property string $uri_icon
 * @property integer $ultimo_hilo_id
 * @property integer $seccion_id
 * @property integer $tablon_id
 * @property ehForoHilo $UltimoHilo
 * @property ehForoSeccion $Seccion
 * @property Doctrine_Collection $Visibles
 * @property ehForoTablon $TablonPadre
 * @property Doctrine_Collection $Subtablones
 * @property Doctrine_Collection $Hilos
 * @property Doctrine_Collection $ehForoTablonModerador
 * @property Doctrine_Collection $Leidos
 * @property Doctrine_Collection $Grupos
 * @property Doctrine_Collection $ehForoStaffTablon
 * @property Doctrine_Collection $SeccionesDelTemplo
 * 
 * @method integer             getId()                            Returns the current record's "id" value
 * @method boolean             getEstadoOculto()                  Returns the current record's "estado_oculto" value
 * @method boolean             getEstadoRestringidoHilos()        Returns the current record's "estado_restringido_hilos" value
 * @method boolean             getEstadoRestringidoRespuestas()   Returns the current record's "estado_restringido_respuestas" value
 * @method integer             getOrdinal()                       Returns the current record's "ordinal" value
 * @method string              getNombre()                        Returns the current record's "nombre" value
 * @method string              getDescripcion()                   Returns the current record's "descripcion" value
 * @method integer             getNumSubtablones()                Returns the current record's "num_subtablones" value
 * @method integer             getNumHilos()                      Returns the current record's "num_hilos" value
 * @method integer             getNumMensajes()                   Returns the current record's "num_mensajes" value
 * @method string              getUriIcon()                       Returns the current record's "uri_icon" value
 * @method integer             getUltimoHiloId()                  Returns the current record's "ultimo_hilo_id" value
 * @method integer             getSeccionId()                     Returns the current record's "seccion_id" value
 * @method integer             getTablonId()                      Returns the current record's "tablon_id" value
 * @method ehForoHilo          getUltimoHilo()                    Returns the current record's "UltimoHilo" value
 * @method ehForoSeccion       getSeccion()                       Returns the current record's "Seccion" value
 * @method Doctrine_Collection getVisibles()                      Returns the current record's "Visibles" collection
 * @method ehForoTablon        getTablonPadre()                   Returns the current record's "TablonPadre" value
 * @method Doctrine_Collection getSubtablones()                   Returns the current record's "Subtablones" collection
 * @method Doctrine_Collection getHilos()                         Returns the current record's "Hilos" collection
 * @method Doctrine_Collection getEhForoTablonModerador()         Returns the current record's "ehForoTablonModerador" collection
 * @method Doctrine_Collection getLeidos()                        Returns the current record's "Leidos" collection
 * @method Doctrine_Collection getGrupos()                        Returns the current record's "Grupos" collection
 * @method Doctrine_Collection getEhForoStaffTablon()             Returns the current record's "ehForoStaffTablon" collection
 * @method Doctrine_Collection getSeccionesDelTemplo()            Returns the current record's "SeccionesDelTemplo" collection
 * @method ehForoTablon        setId()                            Sets the current record's "id" value
 * @method ehForoTablon        setEstadoOculto()                  Sets the current record's "estado_oculto" value
 * @method ehForoTablon        setEstadoRestringidoHilos()        Sets the current record's "estado_restringido_hilos" value
 * @method ehForoTablon        setEstadoRestringidoRespuestas()   Sets the current record's "estado_restringido_respuestas" value
 * @method ehForoTablon        setOrdinal()                       Sets the current record's "ordinal" value
 * @method ehForoTablon        setNombre()                        Sets the current record's "nombre" value
 * @method ehForoTablon        setDescripcion()                   Sets the current record's "descripcion" value
 * @method ehForoTablon        setNumSubtablones()                Sets the current record's "num_subtablones" value
 * @method ehForoTablon        setNumHilos()                      Sets the current record's "num_hilos" value
 * @method ehForoTablon        setNumMensajes()                   Sets the current record's "num_mensajes" value
 * @method ehForoTablon        setUriIcon()                       Sets the current record's "uri_icon" value
 * @method ehForoTablon        setUltimoHiloId()                  Sets the current record's "ultimo_hilo_id" value
 * @method ehForoTablon        setSeccionId()                     Sets the current record's "seccion_id" value
 * @method ehForoTablon        setTablonId()                      Sets the current record's "tablon_id" value
 * @method ehForoTablon        setUltimoHilo()                    Sets the current record's "UltimoHilo" value
 * @method ehForoTablon        setSeccion()                       Sets the current record's "Seccion" value
 * @method ehForoTablon        setVisibles()                      Sets the current record's "Visibles" collection
 * @method ehForoTablon        setTablonPadre()                   Sets the current record's "TablonPadre" value
 * @method ehForoTablon        setSubtablones()                   Sets the current record's "Subtablones" collection
 * @method ehForoTablon        setHilos()                         Sets the current record's "Hilos" collection
 * @method ehForoTablon        setEhForoTablonModerador()         Sets the current record's "ehForoTablonModerador" collection
 * @method ehForoTablon        setLeidos()                        Sets the current record's "Leidos" collection
 * @method ehForoTablon        setGrupos()                        Sets the current record's "Grupos" collection
 * @method ehForoTablon        setEhForoStaffTablon()             Sets the current record's "ehForoStaffTablon" collection
 * @method ehForoTablon        setSeccionesDelTemplo()            Sets the current record's "SeccionesDelTemplo" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehForoTablon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_foro_tablon');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_oculto', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_restringido_hilos', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('estado_restringido_respuestas', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('ordinal', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('num_subtablones', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('num_hilos', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('num_mensajes', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('uri_icon', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('ultimo_hilo_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('seccion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('tablon_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ehForoHilo as UltimoHilo', array(
             'local' => 'ultimo_hilo_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('ehForoSeccion as Seccion', array(
             'local' => 'seccion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ehAuthUser as Visibles', array(
             'refClass' => 'ehForoVisible',
             'local' => 'foro_id',
             'foreign' => 'usuario_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ehForoTablon as TablonPadre', array(
             'local' => 'tablon_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ehForoTablon as Subtablones', array(
             'local' => 'id',
             'foreign' => 'tablon_id'));

        $this->hasMany('ehForoHilo as Hilos', array(
             'local' => 'id',
             'foreign' => 'tablon_id'));

        $this->hasMany('ehForoTablonModerador', array(
             'local' => 'id',
             'foreign' => 'tablon_id'));

        $this->hasMany('ehForoLeidoTablon as Leidos', array(
             'local' => 'id',
             'foreign' => 'tablon_id'));

        $this->hasMany('ehForoGrupo as Grupos', array(
             'refClass' => 'ehForoStaffTablon',
             'local' => 'tablon_id',
             'foreign' => 'grupo_id'));

        $this->hasMany('ehForoStaffTablon', array(
             'local' => 'id',
             'foreign' => 'tablon_id'));

        $this->hasMany('tdhSeccion as SeccionesDelTemplo', array(
             'local' => 'id',
             'foreign' => 'tablon_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'canUpdate' => true,
             ));
        $ehforoforeignkeybackbehavior0 = new ehForoForeignKeyBackBehavior(array(
             'fields' => 
             array(
              0 => 'tablon_id',
             ),
             ));
        $this->actAs($sluggable0);
        $this->actAs($ehforoforeignkeybackbehavior0);
    }
}