<?php

/**
 * tdhArticuloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhArticuloTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhArticuloTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhArticulo');
  }
  
  public function setQueryJoin(Doctrine_Query $q)
  {
    $q->innerJoin('c.Hilo h')
      ->innerJoin('h.PrimerMensaje m')
      ->innerJoin('m.Usuario u')
      ->innerJoin('u.Perfil p');
  }
  
  public function retrieveAutorizadoBySlug($slug)
  {
    $q = $this->createQuery('c');
    $this->setQueryJoin($q);
    
    return $q->addWhere('c.es_aprobado = ?', true)->addWhere('m.slug = ?', $slug)->fetchOne();
  }
}