<?php

/**
 * tdhAsociacionBusquedaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhAsociacionBusquedaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhAsociacionBusquedaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhAsociacionBusqueda');
    }
}