<?php

/**
 * tdhAsociacionUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tdhAsociacionUsuario extends BasetdhAsociacionUsuario
{
  
  public function preInsert($event)
  {
    if($this->contarSocios(false) == 0)
    {
      $this->setRol('administrador');
    }
  }
  
  /**
   * Cuenta el número de socios que hay en la asociación y lo guarda
   * 
   * @param boolean $andSave
   * @return integer Devuelve el número de socios
   */
  public function contarSocios($andSave = true)
  {
    $cuenta = Doctrine_Query::create()->from('tdhAsociacionUsuario')->select('usuario_id')->where('asociacion_id = ?', $this->getAsociacionId())->execute()->count();
    
    if($andSave == true)
    {
      Doctrine_Query::create()->update('tdhAsociacion')->set('num_socios', '?', $cuenta)->where('id = ?', $this->getAsociacionId())->execute();
    }
    
    return $cuenta;
  }
  
  public function postInsert($event)
  {
    $this->contarSocios();
  }
  
  public function postDelete($event)
  {
    $this->contarSocios();
  }
}