<?php

/**
 * tdhAsociacionTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhAsociacionTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhAsociacionTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhAsociacionTipo');
    }
}