<?php

/**
 * tdhAnuncioTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhAnuncioTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhAnuncioTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhAnuncioTipo');
    }
}