<?php

/**
 * tdhAsociacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tdhAsociacion extends BasetdhAsociacion
{  
  protected $misAdministradores; 
  
  protected $misSocios;
  
  /**
   * Comprueba si un usuario pertence a esta asociación.
   * 
   * @param integer $usuario_id
   * @param boolean $forzar Fuerza la búsqueda del usuario entre los socios
   */
  public function esUsuarioIdSocio($usuario_id = null, $forzar = false)
  {
    if($this->Socios && $forzar == false)
    {
      $flag = $this->getSocios()->getFirst() ? true : false;
    }
    else
    {
      // No está implementado
      $flag = false;
    }
    
    return $flag;
  }
  
  public function esUsuarioIdInvitado($usuario_id = null, $forzar = false)
  {
    if($this->Invitaciones && $forzar == false)
    {
      $flag = $this->getInvitaciones()->getFirst() ? true : false;
    }
    else
    {
      // No está implementado
      $flag = false;
    }
    
    return $flag;
  }
  
  
  
  public function esUsuarioIdAdministrador($usuario_id = null)
  {
    if(!isset($this->misAdministradores[$usuario_id]))
    {
      $this->misAdministradores[$usuario_id] = Doctrine::getTable('tdhAsociacionUsuario')->findOneByAsociacionIdAndUsuarioIdAndRol($this->getId(), $usuario_id, 'administrador') ? true : false;
    }
    
    return $this->misAdministradores[$usuario_id];
  }
  
  /**
   * ¿Puede editar el usuario ésta asociación? Si es administrador o es propitario de la asociación, entonces sí.
   * 
   * @param tdhSecurityUser $user
   * @return boolean Verdadero o falso
   */
  public function puedeEditarUsuario(tdhSecurityUser $user)
  {
    if($user->isAuthenticated())
    {
      if($user->isAdministrador())
      {
        return true;
      }
      else
      {
        return $this->esUsuarioIdAdministrador($user->getUserId());
      }
    }
    else
    {
      return false;
    }
  }
  
  public function getImagePath($tam = 'med', $defecto = false)
  {
    $path = '/uploads/assets/asociaciones/'.$this->getId().'-'.$tam.'.png';
  
    if($defecto == false)
    {
      return $path;
    }
    else
    {
      return $this->hasImage($tam) ? $path : '/images/asociaciones/grupo-'.$tam.'.png';
    }
  }
  
  public function hasImage($tam = 'med')
  {
    return file_exists(sfConfig::get('sf_web_dir').$this->getImagePath($tam));
  }
}