<?php

/**
 * tdhArticulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tdhArticulo extends BasetdhArticulo implements tdhContenido
{
  static $routing = 'tdh_articulo';
  
  /**
   * @see tdhContenido::getMensaje()
   */
  public function getMensaje()
  {
    return $this->getHilo()->getPrimerMensaje();
  }
  
  public function getUrlForApp($app)
  {
    return sfProjectConfiguration::getActive()->generaUrlFromApp($app, 'tdh_articulo', array(
    	'slug' => $this->getHilo()->getPrimerMensaje()->getSlug(), 'sf_format' => 'html'
    ));
  }
  
  public function getRouting($enArray = false)
  {
    return sprintf('@%s?slug=%s&sf_format=%s', array($this->getMensaje()->getSlug(), 'html'));
  }
  
  public function getTitular()
  {
    return $this->getMensaje()->getAsunto();
  }
  
  public function getRelacionados()
  {
    // No implementado
    return null;
  }
}