<?php

/**
 * tdhAsociacionInvitacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhAsociacionInvitacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhAsociacionInvitacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhAsociacionInvitacion');
    }
}