<?php

/**
 * tdhAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tdhAnuncio extends BasetdhAnuncio
{
  
  /**
   * @see tdhAnuncio::getNombre()
   * @return string
   */
  public function __toString()
  {
    return $this->getNombre();
  }
  
  /**
   * Devuelve el path del recurso (imagen o flash).
   * 
   * @return string
   */
  public function getRecursoPath()
  {
    if($this->getEsFlash())
    {
      return tdhConfig::get('img_ad_path').'/'.$this->getSlug().'.swf';
    }
    else
    {
      return tdhConfig::get('img_ad_path').'/'.$this->getSlug().'.png';
    }
  }
  
  /**
   * Comprueba si tiene una imagen o flash cargada.
   * 
   * @return boolean
   */
  public function hasRecurso()
  {
    return file_exists(sfConfig::get('sf_web_dir').$this->getRecursoPath());
  }
  
  /**
   * @return boolean
   */
  public function isPagado()
  {
    return !$this->getPago()->isNew();
  }
  
  public function preInsert($event)
  {
    if(!$this->getDesde())
    {
      $this->setDesde(date('Y-m-d H:i:s', time()));
    }
    
    if(!$this->getHasta())
    {
      $this->setHasta(date('Y-m-d H:i:s', time() + 604800)); // 7 días
    }
  }
}
