<?php

/**
 * tdhAsociacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhAsociacionTable extends Doctrine_Table
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhAsociacion');
  }

  public function retrieveByOptionsList(array $options = array())
  {
     $q = $this->createQuery('a');
       
     if(isset($options['usuario_id']) && $options['usuario_id'])
     {  
       $q->leftJoin('a.Socios u WITH u.id = ?', $options['usuario_id'])
         ->leftJoin('a.Invitaciones i WITH i.usuario_id = ?', $options['usuario_id']);
     }
     
     return $q->execute();
  }
  
  /*
  public function retrieveByUsuarioIdList($usuarioId)
  {
    return $this->createQuery('a')
      ->innerJoin('a.Socios u')
      ->where('u.id = ?', $usuarioId)
      ->execute();
  }
  */
}