<?php

/**
 * tdhConsultaTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tdhConsultaTipo extends BasetdhConsultaTipo
{
  public function __toString()
  {
    return $this->getNombre();
  }
  
  /**
   * Comprueba si un usuario dado está autorizado a realizar respuestas y gestión a una consulta.
   * 
   * @param tdhSecurityUser $user
   * @return boolean
   */
  public function esUsuarioAutorizado(tdhSecurityUser $user)
  {
    if($user->isAuthenticated())
    {
      if($user->isAdministrador())
      {
        return true;
      }
      
      foreach($this->getConsultores() as $consultor)
      {
        if($consultor->getUsername() == $user->getUserName())
        {
          return true;
        }
      }
    }
    
    return false;
  }
}