<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhCriticaTable extends tdhContenidoTable
{
  /**
   * Devuelve un registro de un libro básico de la sección dada.
   * 
   * @param integer $seccionId
   */
  public function retrieveBasicoBySeccionId($seccionId)
  {
    return $this->autorizados()
      ->addWhere('c.seccion_id = ?', $seccionId)
      ->addWhere('c.estado_basico = ?', true)
      ->addOrderBy('m.visible_desde DESC, m.created_at DESC')
      ->fetchOne();
  }
}