<?php

/**
 * tdhConsultaRespuestaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhConsultaRespuestaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhConsultaRespuestaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhConsultaRespuesta');
    }
}