<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhCriticaCaptura extends BasetdhCriticaCaptura
{
  protected $ficheroTemp  = null;
  
  /**
   * Setea $ficheroTemp con la ruta de la foto que vamos a grabar
   * 
   * @param string $ficheroTemp Ruta del fichero con la imagen temporal
   */
  public function setFicheroTemp($ficheroTemp)
  {    
    $this->ficheroTemp = $ficheroTemp;
  }
    
  public function getPath($size = 'p')
  {
    $size = $size == 'l' ? 'g' : $size; 
    return tdhConfig::get('img_shot_path').'/'.$this->getCriticaId().$size.'_'.$this->getFichero();
  }
  
  public function existeFichero($size = 'p')
  {
    return file_exists(sfConfig::get('sf_web_dir').$this->getPath($size)); 
  }
  
  /**
   * Guarda una imagen en hasta tres tamaños en función de su altura y anchura.
   */
  protected function guardarCaptura()
  {    
    $captura = new ehUtilesImagen($this->ficheroTemp instanceOf sfValidatedFile ? $this->ficheroTemp->getTempName() : $this->ficheroTemp);
    $captura
      ->setFormatoSalida(ehUtilesImagen::FORMATO_JPEG)
      ->setModoRedimension(ehUtilesImagen::AJUSTE_MEJOR);
    
    if(!$this->fichero)
    {
      $this->setFichero(str_pad($this->getId(), 8, 0, STR_PAD_LEFT).'.jpg');
    }
    
    if($captura->getAnchura() >= 640 || $captura->getAltura() >= 480)
    {
      $captura->setMaxAncho(640)->setMaxAlto(480);
    }
    
    // Tamaño grande
    if($captura->getAnchura() > 430 || $captura->getAltura() > 300)
    {
      $captura->setFicheroDestino(sfConfig::get('sf_web_dir').$this->getPath('g'))->save();
      $this->setTamGra(true);
    }
    
    if($captura->getAnchura() >= 430)
    {
      // Tamaño mediano
      $captura->setMaxAncho(430)->setMaxAlto(300)->setModoRedimension(ehUtilesImagen::AJUSTE_ADAPTATIVO)
        ->setFicheroDestino(sfConfig::get('sf_web_dir').$this->getPath('m'))->save();
      
      $this->setTamMed(true);
    }
    
    // Tamaño pequeño
    $captura->setMaxAncho(175)->setMaxAlto(175)
      ->setFicheroDestino(sfConfig::get('sf_web_dir').$this->getPath('p'))->save();
    
    $this->setTamPeq(true);
    
    return $this;
  }
  
  public function postSave($event)
  {
    if($this->ficheroTemp)
    {
      if(!$this->getFichero())
      {
        $this->guardarCaptura();
        $this->ficheroTemp = null;
        $this->save();
      }
      else
      {
        $this->guardarCaptura();
      }
    }
    
    if($this->getTamMed())
    {
      if($this->getCritica()->getCapturasAutomaticas())
      {
        $this->getCritica()->ponerCapturasEnCuerpo();
      }
    }
  }
  
  public function postDelete($event)
  {
    @unlink(sfConfig::get('sf_web_dir').$this->getPath('p'));
    @unlink(sfConfig::get('sf_web_dir').$this->getPath('m'));
    @unlink(sfConfig::get('sf_web_dir').$this->getPath('g'));
  }
}