<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhCriticaNota extends BasetdhCriticaNota
{
  public function postSave($event)
  {
    $this->getCritica()->calcularNotas();
  }
}