<?php

/**
 * tdhConsultaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhConsultaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhConsultaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhConsulta');
    }
}