<?php

/**
 * tdhConsultaTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhConsultaTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhConsultaTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhConsultaTipo');
    }
}