<?php

/**
 * tdhCriticaVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhCriticaVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhCriticaVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhCriticaVideo');
    }
}