<?php

/**
 * tdhCriticaVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tdhCriticaVideo extends BasetdhCriticaVideo
{
  public function getCode()
  {
    if($this->getMedio() == 'Dailymotion')
    {
      return '';
    }
    // Youtube
    else
    {
      preg_match('%(?:youtube\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i', $this->getUrl(), $match);
      return $match[1];
    }
  }
  
  /**
   * Devuelve el tag HTML necesario para visualizar el vídeo.
   * 
   * @param array $options
   */
  public function getTagHtml(array $options = array())
  {
    switch($this->getMedio())
    {
      case 'Dailymotion':
        return '';
        break;
      case 'Youtube':
      default:
        return sprintf('<iframe width="%s" height="%s" src="http://www.youtube.com/embed/%s?rel=0" frameborder="0" allowfullscreen></iframe>', 632, 356, $this->getCode());
        break;
    }
  }
}