<?php

/**
 * tdhDonacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhDonacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhDonacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhDonacion');
    }
}