<?php

/**
 * tdhEnvioSocialPendienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhEnvioSocialPendienteTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhEnvioSocialPendienteTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhEnvioSocialPendiente');
  }
  
  /**
   * Devuelve una colección de eventos para redes sociales pendientes para enviar ahora.
   * 
   * @return Doctrine_Collection
   */
  public function retrievePendientesList()
  {
    return $this->createQuery('soc')->addWhere('soc.programado_para <= ?', date('Y-m-d H:i:s'))->addOrderBy('soc.programado_para ASC')->execute();
  }
  
  /**
   * Enviar los mensajes pendientes que cumplan con los criterios de fecha, a menos que no se esté en un entorno de producción,
   * en cuyo caso se envía un mensaje informativo al log.
   * 
   * @param string $entorno Entorno de trabajo de la aplicación, por defecto 'prod' de 'producción'
   * @param sfLogger $logger
   * @return integer Número de mensajes enviados a las redes sociales
   */
  public function enviarPendientes($entorno = 'prod', sfLogger $logger = null)
  {
    $contadorEnviados = 0;
    $pendientes = $this->retrievePendientesList();
    
    // Si el entorno es de producción entonces envía los mensajes a las redes sociales
    if(in_array($entorno, tdhConfig::get('entornos_sociales', array('prod'))))
    {      
      if($pendientes->count() > 0)
      {
        foreach($pendientes as $pendiente)
        {
          $pendiente->enviarInmediatamente();
          $contadorEnviados++;
        }
      }
    }
    // Si el entorno NO es de producción, envía un log de depuración para informar que se enviaron unos mensajes simulados
    else
    {
      $logger = !is_null($logger) ? $logger : sfContext::getInstance()->getLogger();
      
      if($pendientes->count() > 0)
      {
        foreach($pendientes as $pendiente)
        {
          $pendiente->delete();
          $contadorEnviados++;
        }
      }
      
      $logger->log("Se enviaron simuladamente $contadorEnviados mensaje(s) a las redes sociales y no se volverán a enviar.");
    }
    
    return $contadorEnviados;
  }
}