<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhEventoApuntadoTable extends Doctrine_Table
{
  public function desapuntar($eventoId, $usuarioId)
  {
    $this->createQuery()
      ->where('evento_id = ?', $eventoId)
      ->addWhere('usuario_id = ?', $usuarioId)->delete()->execute();
  }
}