<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhEventoTable extends tdhContenidoTable
{
  public $opcionesEvento = array(
    'solo_proximos'     => false,
    'orden'							=> 'proximos'
  );
  
  public function setQueryJoin(Doctrine_Query $q)
  {
    $q->innerJoin('c.Hilo h')
      ->innerJoin('h.PrimerMensaje m')
      ->innerJoin('m.Usuario u')
      ->innerJoin('u.Perfil p')
      ->leftJoin('h.Noticia n');
  }
  
  public function setQueryPorOpciones(Doctrine_Query $q, $opciones = array())
  {
    parent::setQueryPorOpciones($q, $opciones);
    
    $opciones = sfToolkit::arrayDeepMerge($this->opcionesEvento, $opciones);
    
    if($opciones['solo_proximos'] == true)
    {
      $q->addWhere('c.fecha_fin >= ?', date('Y-m-d'));
    }
    
    // Fecha inicio
    if(isset($opciones['fecha_inicio']))
    {
      $fecha = $opciones['fecha_inicio'] instanceOf DateTime ? $opciones['fecha_inicio'] : new DateTime($opciones['fecha_inicio']);
      $q->addWhere('c.fecha_fin >= ?', $fecha->format('Y-m-d H:i:s'));
    }
    
    // Fecha fin
    if(isset($opciones['fecha_fin']))
    {
      $fecha = $opciones['fecha_fin'] instanceOf DateTime ? $opciones['fecha_fin'] : new DateTime($opciones['fecha_fin']);
      $q->addWhere('c.fecha_inicio <= ?', $fecha->format('Y-m-d H:i:s'));
    }
    
    switch($opciones['orden'])
    {
      case 'ultimos':
        $q->orderBy('m.visible_desde DESC');
        break;
      case 'proximos':
      default:
        $q->orderBy('c.fecha_inicio ASC');
        break;
    }
  }
  
  /**
   * Devuelve todos los resultados autorizados entre dos fechas dadas
   * 
   * @param DateTime|string $fechaInicio Fecha inicial, mayor que esta fecha son los eventos que saldrán)
   * @param DateTime|string $fechaFin Fecha final, menor o igual que esta fecha son los eventos que saldrán)
   * @return Doctrine_Collection Una colección de registros tdhEvento
   */
  public function getEntreDosFechas($fechaInicio, $fechaFin)
  {
    $q = $this->autorizados();
    
    $this->setQueryPorOpciones($q, array(
      'fecha_inicio'  => $fechaInicio, 
      'fecha_fin'     => $fechaFin
    ));
    
    return $q->execute();
  }
  
  /**
   * Devuelve sólo los próximos eventos.
   * 
   * @return Doctrine_Collection Una colección de registros tdhEvento
   */
  public function getProximos()
  {
    $q = $this->autorizados();
    
    $this->setQueryPorOpciones($q, array(
      'solo_proximos'  => true
    ));
    
    return $q->execute();
  }
}