<?php

/**
 * tdhFeedExternoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhFeedExternoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhFeedExternoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhFeedExterno');
    }
}