<?php

/**
 * tdhLicencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 */
class tdhLicencia extends BasetdhLicencia
{
  public function __toString()
  {
    return $this->getNombre();
  }
}