<?php

/**
 * tdhMailMensajeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhMailMensajeTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhMailMensajeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhMailMensaje');
  }
  
  /**
   * Borra todos los registros de la tabla 
   */
  public function deleteAll()
  {
    $this->createQuery()->delete()->execute();
  }
}