<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhMenuTable extends Doctrine_Table
{
  public function getForPortada()
  {
    $q = $this->createQuery('m')
      ->where('m.estado_portada = ?', true)
      ->orderBy('m.ordinal DESC')
      ->orderBy('m.id DESC');
      
    return $q->execute();
  }
}