<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhNoticiaTable extends tdhContenidoTable
{
  public function setQueryJoin(Doctrine_Query $q)
  {
    $q->innerJoin('c.Hilo h')
      ->innerJoin('h.PrimerMensaje m')
      ->innerJoin('m.Usuario u')
      ->innerJoin('u.Perfil p')
      ->innerJoin('c.Seccion s')
      ->leftJoin('h.Recurso r')
      ->leftJoin('h.Critica i')
      ->leftJoin('h.Evento e');
  }
}