<?php

/**
 * tdhOauthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhOauthTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhOauthTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhOauth');
  }
  
  public function retrieveOneByUsernameAndServicio($username, $servicio)
  {
    return $this->createQuery('o')->innerJoin('o.Usuario u')
      ->addWhere('o.servicio = ?', $servicio)->addWhere('u.username = ?', $username)
      ->fetchOne();
  }
}