<?php

/**
 * tdhPerfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhPerfilTable extends ehForoPerfilTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhPerfilTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhPerfil');
  }
  
  public function retrieveForBoletin($todos = false, $offset = null, $limit = null)
  {
    $q = $this->createQuery('p')->innerJoin('p.Usuario u')->groupBy('p.email')->orderBy('u.created_at DESC');
    
    if(!$todos)
    {
      $q->addWhere('p.boletines = ?', true);
    }
    
    if(!empty($offset))
    {
      $q->offset($offset);
    }
    
    if(!empty($limit))
    {
      $q->limit($limit);
    }
    
    return $q->execute();
  }
}