<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhPopularTable extends Doctrine_Table
{
  public function incrementarPopularidadPorSeccionSlug($seccionSlug)
  {
    $filas = $this->createQuery('p')
      ->innerJoin('p.Seccion s ON p.seccion_id = s.id')
      ->set('p.visitas', 'p.visitas + 1')
      ->where('p.fecha = ?', date('Y-m-d'))
      ->addWhere('s.slug = ?', $seccionSlug)->update()->execute();
    
    if($filas == 0)
    {
      if($seccion = Doctrine::getTable('tdhSeccion')->findOneBySlug($seccionSlug))
      {
        $popular = new tdhPopular();
        $popular->setSeccionId($seccion->getId())
                ->setFecha(date('Y-m-d'))
                ->setVisitas(1)
                ->save();
      }
      else
      {
        // Enviamos un mensaje al log para informar de que la sección no existe.
        if (sfConfig::get('sf_logging_enabled'))
        {
          sfContext::getInstance()->getLogger()->warning('No existe esa sección en nuestra base de datos y no se puede incrementar su popularidad.');
        }
      }
    }
  }
  
  public function retrieveBackendList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    
    return $q->innerJoin($rootAlias.'.Seccion s');
  }
}