<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhRecursoTipo extends BasetdhRecursoTipo
{
  public function __toString()
  {
    return $this->getNombre();
  }
}