<?php

/**
 * tdhRecursoFavorito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class tdhRecursoFavorito extends BasetdhRecursoFavorito
{
  protected function updateFavoritosOfRecurso()
  {
    $favoritos = Doctrine::getTable('tdhRecursoFavorito')->retrieveCountsByRecursoId($this->getRecursoId());
    Doctrine_Query::create()->update('tdhRecurso')->set('favoritos', '?', $favoritos)->addWhere('id = ?', $this->getRecursoId())->execute();
  }
  
  public function postInsert($event)
  {
    $this->updateFavoritosOfRecurso();
  }
  
  public function postDelete($event)
  {
    $this->updateFavoritosOfRecurso();
  }
}