<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhRecursoTable extends tdhContenidoTable
{
  public function setQueryJoin(Doctrine_Query $q)
  {
    parent::setQueryJoin($q);
    $q->innerJoin('c.Tipo t');
  }
  
  public function setQueryPorOpciones(Doctrine_Query $q, $opciones = array())
  {
    $opciones = parent::setQueryPorOpciones($q, $opciones);
    
    // Left join con la tabla de favoritos de usuario para recursos
    if($opciones['favorito_ruser_id'])
    {
      $q->leftJoin($q->getRootAlias().'.FavoritoDeUsuarios fur WITH fur.id = ?', $opciones['favorito_ruser_id']);
    }
    
    if($opciones['perfil'])
    {
      $q->innerJoin($q->getRootAlias().'.FavoritoDeUsuarios pur WITH pur.username = ?', $opciones['perfil']);
    }
  }
}