<?php

/**
 * tdhRecursoFavoritoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhRecursoFavoritoTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhRecursoFavoritoTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhRecursoFavorito');
  }
  
  /**
  * Cuenta el número de favoritos que tiene un recurso.
  *
  * @param integer $id
  * @return integer
  */
  public function retrieveCountsByRecursoId($id)
  {
    $result = $this->createQuery('rf')->addWhere('rf.recurso_id = ?', $id)->select('COUNT(rf.recurso_id) AS favoritos')->fetchOne();
    return $result->getFavoritos();
  }
}