<?php

/**
 * tdhSorteoParticipanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhSorteoParticipanteTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhSorteoParticipanteTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhSorteoParticipante');
  }
  
  /**
   * Devuelve el último número asignado a un participante.
   * 
   * @param integer $sorteoId Identificador numérico del sorteo en la base de datos
   * @return integer
   */
  public function retrieveUltimoNumeroParticipante($sorteoId)
  {
    if($participante = $this->createQuery('p')->addWhere('p.sorteo_id = ?', $sorteoId)->orderBy('p.numero DESC')->select('p.id, p.numero')->fetchOne())
    {
      return $participante->getNumero();
    }
    
    return 0;
  }
  
  public function retrieveBackendList(Doctrine_Query $q)
  {
    return $q->innerJoin($q->getRootAlias().'.Sorteo s');
  }
  
  public function retrieveGanadorBySemilla($sorteoId, $semilla)
  {
    return $this->createQuery('p')->addWhere('p.sorteo_id = ?', $sorteoId)->orderBy("RAND($semilla)")->fetchOne();
  }
}