<?php

/**
 * tdhSorteoCondicionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhSorteoCondicionTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhSorteoCondicionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhSorteoCondicion');
  }
  
  public function retrieveListBySorteoIdAndServicio($sorteoId, $servicio = 'twitter')
  {
    return $this->createQuery('c')->addWhere('c.sorteo_id = ?', $sorteoId)->addWhere('c.tipo = ?', $servicio)->execute();
  }
  
  public function retrieveBackendList(Doctrine_Query $q)
  {
    return $q->innerJoin($q->getRootAlias().'.Sorteo s');
  }
}