<?php

/**
 * tdhSorteoUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhSorteoUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tdhSorteoUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tdhSorteoUsuario');
    }
}