<?php

/**
 * tdhSeccionFavoritaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tdhSeccionFavoritaTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object tdhSeccionFavoritaTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('tdhSeccionFavorita');
  }
  
  /**
   * Cuenta el número de favoritos que tiene una sección.
   * 
   * @param integer $id
   * @return integer
   */
  public function retrieveCountsBySeccionId($id)
  {
    $result = $this->createQuery('sf')->addWhere('sf.seccion_id = ?', $id)->select('COUNT(sf.seccion_id) AS favoritos')->fetchOne();
    return $result->getFavoritos();
  }
}