<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ehAuthUser', 'doctrine');

/**
 * BaseehAuthUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $salt
 * @property string $password
 * @property timestamp $last_login
 * @property string $last_ip_address
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property string $remember_key
 * @property Doctrine_Collection $Credentials
 * @property Doctrine_Collection $ehAuthCredentialUser
 * @property Doctrine_Collection $VisiblesTablones
 * @property Doctrine_Collection $Mensajes
 * @property ehForoPerfil $Perfil
 * @property Doctrine_Collection $Invitados
 * @property Doctrine_Collection $Invitantes
 * @property Doctrine_Collection $ehForoTablonModerador
 * @property Doctrine_Collection $HilosLeidos
 * @property Doctrine_Collection $TablonesLeidos
 * @property Doctrine_Collection $Grupos
 * @property Doctrine_Collection $ehForoGrupoUsuario
 * @property Doctrine_Collection $MensajesPrivados
 * @property Doctrine_Collection $HiloSeguimientos
 * @property Doctrine_Collection $RegistrosKarma
 * @property ehForoUsuarioActivo $UsuarioActivo
 * @property Doctrine_Collection $Participante
 * @property Doctrine_Collection $Autentificaciones
 * @property Doctrine_Collection $SeccionesFavoritas
 * @property Doctrine_Collection $Eventos
 * @property Doctrine_Collection $RecursosFavoritos
 * @property Doctrine_Collection $Donaciones
 * @property Doctrine_Collection $Notas
 * @property Doctrine_Collection $ConsultaTipos
 * @property Doctrine_Collection $Consultas
 * @property Doctrine_Collection $RespuestasConsultas
 * @property Doctrine_Collection $PagosAnuncio
 * @property Doctrine_Collection $Asociaciones
 * @property tdhAsociacionBusqueda $PeticionGrupo
 * @property Doctrine_Collection $InvitacionesAsociacion
 * 
 * @method integer               getId()                     Returns the current record's "id" value
 * @method string                getUsername()               Returns the current record's "username" value
 * @method string                getSalt()                   Returns the current record's "salt" value
 * @method string                getPassword()               Returns the current record's "password" value
 * @method timestamp             getLastLogin()              Returns the current record's "last_login" value
 * @method string                getLastIpAddress()          Returns the current record's "last_ip_address" value
 * @method boolean               getIsActive()               Returns the current record's "is_active" value
 * @method boolean               getIsSuperAdmin()           Returns the current record's "is_super_admin" value
 * @method string                getRememberKey()            Returns the current record's "remember_key" value
 * @method Doctrine_Collection   getCredentials()            Returns the current record's "Credentials" collection
 * @method Doctrine_Collection   getEhAuthCredentialUser()   Returns the current record's "ehAuthCredentialUser" collection
 * @method Doctrine_Collection   getVisiblesTablones()       Returns the current record's "VisiblesTablones" collection
 * @method Doctrine_Collection   getMensajes()               Returns the current record's "Mensajes" collection
 * @method ehForoPerfil          getPerfil()                 Returns the current record's "Perfil" value
 * @method Doctrine_Collection   getInvitados()              Returns the current record's "Invitados" collection
 * @method Doctrine_Collection   getInvitantes()             Returns the current record's "Invitantes" collection
 * @method Doctrine_Collection   getEhForoTablonModerador()  Returns the current record's "ehForoTablonModerador" collection
 * @method Doctrine_Collection   getHilosLeidos()            Returns the current record's "HilosLeidos" collection
 * @method Doctrine_Collection   getTablonesLeidos()         Returns the current record's "TablonesLeidos" collection
 * @method Doctrine_Collection   getGrupos()                 Returns the current record's "Grupos" collection
 * @method Doctrine_Collection   getEhForoGrupoUsuario()     Returns the current record's "ehForoGrupoUsuario" collection
 * @method Doctrine_Collection   getMensajesPrivados()       Returns the current record's "MensajesPrivados" collection
 * @method Doctrine_Collection   getHiloSeguimientos()       Returns the current record's "HiloSeguimientos" collection
 * @method Doctrine_Collection   getRegistrosKarma()         Returns the current record's "RegistrosKarma" collection
 * @method ehForoUsuarioActivo   getUsuarioActivo()          Returns the current record's "UsuarioActivo" value
 * @method Doctrine_Collection   getParticipante()           Returns the current record's "Participante" collection
 * @method Doctrine_Collection   getAutentificaciones()      Returns the current record's "Autentificaciones" collection
 * @method Doctrine_Collection   getSeccionesFavoritas()     Returns the current record's "SeccionesFavoritas" collection
 * @method Doctrine_Collection   getEventos()                Returns the current record's "Eventos" collection
 * @method Doctrine_Collection   getRecursosFavoritos()      Returns the current record's "RecursosFavoritos" collection
 * @method Doctrine_Collection   getDonaciones()             Returns the current record's "Donaciones" collection
 * @method Doctrine_Collection   getNotas()                  Returns the current record's "Notas" collection
 * @method Doctrine_Collection   getConsultaTipos()          Returns the current record's "ConsultaTipos" collection
 * @method Doctrine_Collection   getConsultas()              Returns the current record's "Consultas" collection
 * @method Doctrine_Collection   getRespuestasConsultas()    Returns the current record's "RespuestasConsultas" collection
 * @method Doctrine_Collection   getPagosAnuncio()           Returns the current record's "PagosAnuncio" collection
 * @method Doctrine_Collection   getAsociaciones()           Returns the current record's "Asociaciones" collection
 * @method tdhAsociacionBusqueda getPeticionGrupo()          Returns the current record's "PeticionGrupo" value
 * @method Doctrine_Collection   getInvitacionesAsociacion() Returns the current record's "InvitacionesAsociacion" collection
 * @method ehAuthUser            setId()                     Sets the current record's "id" value
 * @method ehAuthUser            setUsername()               Sets the current record's "username" value
 * @method ehAuthUser            setSalt()                   Sets the current record's "salt" value
 * @method ehAuthUser            setPassword()               Sets the current record's "password" value
 * @method ehAuthUser            setLastLogin()              Sets the current record's "last_login" value
 * @method ehAuthUser            setLastIpAddress()          Sets the current record's "last_ip_address" value
 * @method ehAuthUser            setIsActive()               Sets the current record's "is_active" value
 * @method ehAuthUser            setIsSuperAdmin()           Sets the current record's "is_super_admin" value
 * @method ehAuthUser            setRememberKey()            Sets the current record's "remember_key" value
 * @method ehAuthUser            setCredentials()            Sets the current record's "Credentials" collection
 * @method ehAuthUser            setEhAuthCredentialUser()   Sets the current record's "ehAuthCredentialUser" collection
 * @method ehAuthUser            setVisiblesTablones()       Sets the current record's "VisiblesTablones" collection
 * @method ehAuthUser            setMensajes()               Sets the current record's "Mensajes" collection
 * @method ehAuthUser            setPerfil()                 Sets the current record's "Perfil" value
 * @method ehAuthUser            setInvitados()              Sets the current record's "Invitados" collection
 * @method ehAuthUser            setInvitantes()             Sets the current record's "Invitantes" collection
 * @method ehAuthUser            setEhForoTablonModerador()  Sets the current record's "ehForoTablonModerador" collection
 * @method ehAuthUser            setHilosLeidos()            Sets the current record's "HilosLeidos" collection
 * @method ehAuthUser            setTablonesLeidos()         Sets the current record's "TablonesLeidos" collection
 * @method ehAuthUser            setGrupos()                 Sets the current record's "Grupos" collection
 * @method ehAuthUser            setEhForoGrupoUsuario()     Sets the current record's "ehForoGrupoUsuario" collection
 * @method ehAuthUser            setMensajesPrivados()       Sets the current record's "MensajesPrivados" collection
 * @method ehAuthUser            setHiloSeguimientos()       Sets the current record's "HiloSeguimientos" collection
 * @method ehAuthUser            setRegistrosKarma()         Sets the current record's "RegistrosKarma" collection
 * @method ehAuthUser            setUsuarioActivo()          Sets the current record's "UsuarioActivo" value
 * @method ehAuthUser            setParticipante()           Sets the current record's "Participante" collection
 * @method ehAuthUser            setAutentificaciones()      Sets the current record's "Autentificaciones" collection
 * @method ehAuthUser            setSeccionesFavoritas()     Sets the current record's "SeccionesFavoritas" collection
 * @method ehAuthUser            setEventos()                Sets the current record's "Eventos" collection
 * @method ehAuthUser            setRecursosFavoritos()      Sets the current record's "RecursosFavoritos" collection
 * @method ehAuthUser            setDonaciones()             Sets the current record's "Donaciones" collection
 * @method ehAuthUser            setNotas()                  Sets the current record's "Notas" collection
 * @method ehAuthUser            setConsultaTipos()          Sets the current record's "ConsultaTipos" collection
 * @method ehAuthUser            setConsultas()              Sets the current record's "Consultas" collection
 * @method ehAuthUser            setRespuestasConsultas()    Sets the current record's "RespuestasConsultas" collection
 * @method ehAuthUser            setPagosAnuncio()           Sets the current record's "PagosAnuncio" collection
 * @method ehAuthUser            setAsociaciones()           Sets the current record's "Asociaciones" collection
 * @method ehAuthUser            setPeticionGrupo()          Sets the current record's "PeticionGrupo" value
 * @method ehAuthUser            setInvitacionesAsociacion() Sets the current record's "InvitacionesAsociacion" collection
 * 
 * @package    templodehecate
 * @subpackage model
 * @author     Pablo Floriano <kether@templodehecate.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseehAuthUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eh_auth_user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('last_ip_address', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '127.0.0.1',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('remember_key', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 128,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ehAuthCredential as Credentials', array(
             'refClass' => 'ehAuthCredentialUser',
             'local' => 'user_id',
             'foreign' => 'credential_id'));

        $this->hasMany('ehAuthCredentialUser', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ehForoTablon as VisiblesTablones', array(
             'refClass' => 'ehForoVisible',
             'local' => 'usuario_id',
             'foreign' => 'foro_id'));

        $this->hasMany('ehForoMensaje as Mensajes', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasOne('ehForoPerfil as Perfil', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('ehForoAmigo as Invitados', array(
             'local' => 'id',
             'foreign' => 'invitante_id'));

        $this->hasMany('ehForoAmigo as Invitantes', array(
             'local' => 'id',
             'foreign' => 'invitado_id'));

        $this->hasMany('ehForoTablonModerador', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('ehForoLeidoHilo as HilosLeidos', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('ehForoLeidoTablon as TablonesLeidos', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('ehForoGrupo as Grupos', array(
             'refClass' => 'ehForoGrupoUsuario',
             'local' => 'usuario_id',
             'foreign' => 'grupo_id'));

        $this->hasMany('ehForoGrupoUsuario', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('ehForoMensajePrivado as MensajesPrivados', array(
             'local' => 'id',
             'foreign' => 'usuario_destino_id'));

        $this->hasMany('ehForoHiloSeguimiento as HiloSeguimientos', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('ehForoKarma as RegistrosKarma', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasOne('ehForoUsuarioActivo as UsuarioActivo', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('tdhSorteoParticipante as Participante', array(
             'refClass' => 'tdhSorteoUsuario',
             'local' => 'usuario_id',
             'foreign' => 'participante_id'));

        $this->hasMany('tdhOauth as Autentificaciones', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('tdhSeccion as SeccionesFavoritas', array(
             'refClass' => 'tdhSeccionFavorita',
             'local' => 'usuario_id',
             'foreign' => 'seccion_id'));

        $this->hasMany('tdhEvento as Eventos', array(
             'refClass' => 'tdhEventoApuntado',
             'local' => 'usuario_id',
             'foreign' => 'evento_id'));

        $this->hasMany('tdhRecurso as RecursosFavoritos', array(
             'refClass' => 'tdhRecursoFavorito',
             'local' => 'usuario_id',
             'foreign' => 'recurso_id'));

        $this->hasMany('tdhDonacion as Donaciones', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('tdhCriticaNota as Notas', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('tdhConsultaTipo as ConsultaTipos', array(
             'refClass' => 'tdhConsultaTipoUsuario',
             'local' => 'usuario_id',
             'foreign' => 'tipo_id'));

        $this->hasMany('tdhConsulta as Consultas', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('tdhConsultaRespuesta as RespuestasConsultas', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('tdhAnuncioPago as PagosAnuncio', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('tdhAsociacion as Asociaciones', array(
             'refClass' => 'tdhAsociacionUsuario',
             'local' => 'usuario_id',
             'foreign' => 'asociacion_id'));

        $this->hasOne('tdhAsociacionBusqueda as PeticionGrupo', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('tdhAsociacionInvitacion as InvitacionesAsociacion', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}