generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tdhSorteoParticipante
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tdh_sorteo_participante
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        ip:                { label: 'Dirección IP' }
        created_at:        { label: 'Fecha' }
        email:             { label: 'Correo electrónico' }
        numero:            { label: 'Número' }
      list:    
        title:             'Lista de participantes'
        display:           [tipo, numero, nombre, email, sorteo, created_at]
        table_method:      retrieveBackendList
      filter:
        display:           [ip, numero, nombre, email, tipo, sorteo_id]
      form:    ~
      edit:    
        title:             'Editar participante %%nombre%%'
      new:     
        title:             'Nuevo participante'
