<?php

/**
 * PluginehForoHiloSeguimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginehForoHiloSeguimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginehForoHiloSeguimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginehForoHiloSeguimiento');
    }
}