<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginehForoLeidoHiloTable extends Doctrine_Table
{
  /**
   * Devuelve un registro en la tabla ehForoLeidoHilo si hay correspondencia con el usuarioId y el hiloId.
   * 
   * @param integer $usuarioId Identificador numérico de la tabla ehAuthUser
   * @param integer $hiloId Identificador numérico de la tabla ehForoHilo
   * @return mixed Un objeto ehForoLeidoHilo o null si no hay correspondencia
   */
  public function retrievePorUsuarioIdAndHiloId($usuarioId, $hiloId)
  {
    return $this->createQuery('l')
      ->where('l.usuario_id = ?', $usuarioId)
      ->addWhere('l.hilo_id = ?', $hiloId)
      ->fetchOne();
  }
}