<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginehForoTablon extends BaseehForoTablon
{  
  
  protected $misSubforos = null;
  
  protected $oldTablonId = null;
  
  public function __toString()
  {
    return $this->getNombre();
  }
  
  public function getMisSubforos(sfUser $user = null)
  {
    if(!$this->misSubforos)
    {
      $this->misSubforos = Doctrine::getTable('ehForoTablon')->retrieveSubtablones($this->getId(), $user);
    }
    
    return $this->misSubforos;
  }
  
  public function getUltimoMensajeByUltimoHilo(Doctrine_Connection $conn = null)
  {
    return $this->getUltimoHiloId() ? $this->getUltimoHilo($conn)->getUltimoMensaje($conn) : null;
  }
  
  public function getPrimerMensajeByUltimoHilo(Doctrine_Connection $conn = null)
  {
    return $this->getUltimoHiloId() ? $this->getUltimoHilo($conn)->getPrimerMensaje($conn) : null;
  }
  
  /**
   * Comprueba si el usuario, si está autentificado, ha leído el foro 
   * 
   * @return boolean Verdadero o falso
   */
  public function esLeido(Doctrine_Connection $conn = null)
  {
    return is_null($this->getUltimoHiloId()) ? true : 
      ($this->getPrimerLeido($conn) ? 
        ($this->getPrimerLeido($conn)->getReadAt() >= $this->getUltimoMensajeByUltimoHilo($conn)->getCreatedAt() ? true : false) : 
        false);
  }
  
  public function leidoPorUsuarioId($usuarioId, Doctrine_Connection $conn = null)
  {
    if(!$this->esLeido($conn))
    {
      if(!($leido = $this->getPrimerLeido($conn)))
      {
        $leido = new ehForoLeidoTablon();
        $leido->setUsuarioId($usuarioId);
        $leido->setTablonId($this->getId());
      }
      
      $leido->setReadAt(date('Y-m-d H:i:s'));
      $leido->save($conn);
    }
  }
  
  public function getPrimerLeido(Doctrine_Connection $conn = null, $forzarConsulta = true)
  {
    try
    {
      return isset($this->Leidos) ? $this->getLeidos($conn)->getFirst() : null;
    }
    catch(Doctrine_Exception $e)
    {
      return null;
    }
  }
  
  public function searchAndSetHilos()
  {
    $ultimoMensaje = Doctrine::getTable('ehForoMensaje')
      ->createQuery('m')
      ->innerJoin('m.Hilo h')
      ->where('h.tablon_id = ?', $this->getId())
      ->orderBy('m.created_at DESC')
      ->fetchOne();
    
    if($ultimoMensaje)
    {      
      $this->setUltimoHilo($ultimoMensaje->getHilo());
      $this->save();
    }
    
    return $this;
  }
  
  public function getPagerHilos($pagina = 1, $opciones = array())
  {
    $pager = new sfDoctrinePager('ehForoHilo', ehForoConfig::getStatic('temas_por_pagina'));
    $pager->setPage($pagina);
    $pager->setTableMethod('autorizados');
    $pager->setParameter('links', ehForoConfig::getStatic('links_temas_por_pagina'));
    
    $q = $pager->getQuery();
    ehForoHiloTable::setQuerySelectMinimo($q);
    
    $q->addWhere('h.tablon_id = ?', $this->getId())
      ->addOrderBy('um.visible_desde DESC, um.created_at DESC, um.id DESC');
    
    if(isset($opciones['usuario_id']))
    {
      if(!is_null($opciones['usuario_id']))
      {
        ehForoHiloTable::setQueryLeido($q, $opciones['usuario_id'], $this->getId());
      }
    }
    
    $pager->init();
    
    return $pager;
  }
  
  public function setTablonId($value)
  {
    $this->oldTablonId = $this->getTablonId();
    parent::_set('tablon_id', $value);
  }
  
  public function postInsert($event)
  {
    // Si no contamos el nuevo número de tablones
    if($this->getTablonId())
    {
      $this->getTablonPadre()->setNumSubtablones(Doctrine::getTable('ehForoTablon')->numeroDeSubTablones($this->getTablonId()))->save();
    }
  }
  
  public function postDelete($event)
  {
    if($this->getId() != $this->getTablonId())
    {
      $this->getTablonPadre()->setNumSubtablones(Doctrine::getTable('ehForoTablon')->numeroDeSubTablones($this->getTablonId()))->save();
    }
  }
  
  public function postUpdate($event)
  {
    if(!is_null($this->oldTablonId) && ($this->getTablonId() != $this->oldTablonId))
    {
      Doctrine_Query::create()->update('ehForoTablon')
        ->set('num_subtablones', '?', Doctrine::getTable('ehForoTablon')->numeroDeSubTablones($this->getTablonId()))->where('id = ?', $this->getTablonId())
        ->execute();
      
      Doctrine_Query::create()->update('ehForoTablon')
        ->set('num_subtablones', '?', Doctrine::getTable('ehForoTablon')->numeroDeSubTablones($this->oldTablonId))->where('id = ?', $this->oldTablonId)
        ->execute();
    }
  }
  
}