<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginehForoUsuarioActivoTable extends Doctrine_Table
{
  public function getEnOrden()
  {
    return $this->createQuery('a')->leftJoin('a.Usuario u')->leftJoin('u.Perfil p')->orderBy('u.username ASC')->execute();
  }
}