<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginehForoPerfilTable extends Doctrine_Table
{
  public function retrievePorUsername($username)
  {
    return $this->createQuery('p')->innerJoin('p.Usuario u')->where('u.username = ?', $username)->fetchOne();
  }
  
  public function retrievePorUsernameOrEmail($username, $email)
  {
    return $this->createQuery('p')->innerJoin('p.Usuario u')->where('u.username = ?', $username)->orWhere('p.email = ?', $email)->fetchOne();
  }
  
  public function retrievePagerUsers($pagina = 1, $opciones = array())
  {
    $pager = new sfDoctrinePager('ehAuthUser', 15);
    
    $pager->setPage($pagina);
    $pager->getQuery()
      ->innerJoin($pager->getQuery()->getRootAlias().'.Perfil p')->addOrderBy($pager->getQuery()->getRootAlias().'.username ASC');
   
    if(
      isset($opciones['user']) && 
      $opciones['user'] instanceOf tdhSecurityUser &&
      $opciones['user']->isAuthenticated() 
      )
    {
      $pager->getQuery()
        ->leftJoin($pager->getQuery()->getRootAlias().'.Invitantes v WITH v.invitante_id = ?', $opciones['user']->getUserId());
    }
    
    if(isset($opciones['username']) && $opciones['username'])
    {
      $pager->getQuery()->addWhere($pager->getQuery()->getRootAlias().'.username != ?', $opciones['username']);
      $pager->getQuery()
        ->innerJoin($pager->getQuery()->getRootAlias().'.Invitantes z')
        ->innerJoin('z.Invitante uz WITH uz.username = ?', $opciones['username']);
    }
    
    $pager->init();
    
    return $pager;
  }
}