<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginehForoMensajePrivado extends BaseehForoMensajePrivado
{
  public function getDestinatarioNick()
  {
    return $this->getDestinatario()->getPerfil()->getNick() ? $this->getDestinatario()->getPerfil()->getNick() : $this->getDestinatario()->getUsername();
  }
  
  /**
   * Devuelve el ID del usuario de procedencia del mensaje privado.
   * 
   * @return integer 
   */
  public function getUsuarioProcedenciaId()
  {
    return $this->getMensaje()->getUsuarioId();
  }
}