<?php

/**
 * PluginehForoGrupoUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginehForoGrupoUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginehForoGrupoUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginehForoGrupoUsuario');
    }
}