<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginehForoMensajePrivadoTable extends Doctrine_Table
{
  public function countNuevosPorUsuarioId($usuarioId)
  {
    return $this->createQuery('n')
      ->addWhere('n.usuario_destino_id = ?', $usuarioId)
      ->addWhere('n.estado_borrado_destino = ?', false)
      ->addWhere('n.estado_leido = ?', false)
      ->count();
  }
  
  protected function conjunto()
  {
    return $this->createQuery('mp')
      ->innerJoin('mp.Mensaje m')
      ->leftJoin('m.Usuario u')
      ->leftJoin('u.Perfil p')
      ->innerJoin('mp.Destinatario d')
      ->innerJoin('d.Perfil');
  }
  
  public function autorizadosRecibidos()
  {
    return $this->conjunto()
      ->addWhere('mp.estado_borrado_destino = ?', false);
  }
  
  public function autorizadosEnviados()
  {
    return $this->conjunto()
      ->addWhere('mp.estado_borrado_procedencia = ?', false);
  }
  
  public function retrievePorId($id)
  {
    return $this->conjunto()->where('id = ?', $id)->fetchOne();
  }
}