<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginehForoSeccion extends BaseehForoSeccion
{
  protected $tablonesEnOrden = null;
  
  public function __toString()
  {
    return $this->getNombre();
  }
  
  public function getTablonesEnOrden(sfUser $user = null)
  {
    if(!$this->tablonesEnOrden)
      $this->tablonesEnOrden = Doctrine::getTable('ehForoTablon')->getEnOrdenPorSeccionId($this->getId(), $user);
    
    return $this->tablonesEnOrden;
  }
}