<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginehForoUsuarioActivo extends BaseehForoUsuarioActivo
{  
  public function __toString()
  {
    return (string) $this->getUpdatedAt();
  }
  
  public function actualizarRegistro(sfContext $context)
  {
    try
    {
      $user     = $context->getUser();
      
      $this->setIp($user->getIp());
      $this->setAgent((string) $user->getAgent());

      $this->setUsuarioId($user->isAuthenticated() ? $user->getUserId() : null);
      $this->setUpdatedAt(date('Y-m-d H:i:s'));
      
      $this->setModulo($context->getModuleName());
      $this->setAccion($context->getActionName());
      
      $this->save();
    }
    catch(sfException $e)
    {
    }
        
    $this->borrarActivosAntiguos();
  }
  
  /**
   * Borrar todos los usuario cuya actividad haya caducado según el parámetro especificado en "eh_foro_usuario_activo_timeout"
   */
  public function borrarActivosAntiguos()
  {
    Doctrine_Query::create()
      ->delete('ehForoUsuarioActivo')
      ->where('updated_at < ?', date('Y-m-d H:i:s', (time()-ehForoConfig::getStatic('usuario_activo_timeout'))))
      ->execute();
  }
  
  public function getNick()
  {
    return !$this->getUsuarioId() ? 'Invitado' : $this->getUsuario()->getPerfil()->getNick() ? $this->getUsuario()->getPerfil()->getNick() : $this->getUsuario()->getUsername();
  }
}