<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginehForoSeccionTable extends Doctrine_Table
{
  public function getEnOrden()
  {
    $q = $this->createQuery('s')
      ->where('s.estado_oculto = ?', false)
      ->addOrderBy('s.ordinal DESC, s.nombre ASC');
            
    return $q->execute();
  }
}