<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tdh_consulta', 'tdh_consulta_usuario_id_eh_auth_user_id', array(
             'name' => 'tdh_consulta_usuario_id_eh_auth_user_id',
             'local' => 'usuario_id',
             'foreign' => 'id',
             'foreignTable' => 'eh_auth_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tdh_consulta_respuesta', 'tdh_consulta_respuesta_usuario_id_eh_auth_user_id', array(
             'name' => 'tdh_consulta_respuesta_usuario_id_eh_auth_user_id',
             'local' => 'usuario_id',
             'foreign' => 'id',
             'foreignTable' => 'eh_auth_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tdh_consulta_respuesta', 'tdh_consulta_respuesta_consulta_id_tdh_consulta_id', array(
             'name' => 'tdh_consulta_respuesta_consulta_id_tdh_consulta_id',
             'local' => 'consulta_id',
             'foreign' => 'id',
             'foreignTable' => 'tdh_consulta',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tdh_consulta', 'tdh_consulta_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->addIndex('tdh_consulta_respuesta', 'tdh_consulta_respuesta_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->addIndex('tdh_consulta_respuesta', 'tdh_consulta_respuesta_consulta_id', array(
             'fields' => 
             array(
              0 => 'consulta_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tdh_consulta', 'tdh_consulta_usuario_id_eh_auth_user_id');
        $this->dropForeignKey('tdh_consulta_respuesta', 'tdh_consulta_respuesta_usuario_id_eh_auth_user_id');
        $this->dropForeignKey('tdh_consulta_respuesta', 'tdh_consulta_respuesta_consulta_id_tdh_consulta_id');
        $this->removeIndex('tdh_consulta', 'tdh_consulta_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->removeIndex('tdh_consulta_respuesta', 'tdh_consulta_respuesta_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->removeIndex('tdh_consulta_respuesta', 'tdh_consulta_respuesta_consulta_id', array(
             'fields' => 
             array(
              0 => 'consulta_id',
             ),
             ));
    }
}