<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('tdh_consulta', 'usuario');
        $this->addColumn('tdh_consulta', 'email', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->addColumn('tdh_consulta', 'ip', 'string', '255', array(
             'notnull' => '1',
             'default' => '127.0.0.1',
             ));
        $this->addColumn('tdh_consulta', 'usuario_id', 'integer', '4', array(
             'notnull' => '',
             ));
        $this->addColumn('tdh_consulta_respuesta', 'ip', 'string', '255', array(
             'notnull' => '1',
             'default' => '127.0.0.1',
             ));
        $this->addColumn('tdh_consulta_respuesta', 'usuario_id', 'integer', '4', array(
             'notnull' => '',
             ));
        $this->addColumn('tdh_consulta_respuesta', 'consulta_id', 'integer', '4', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('tdh_consulta', 'usuario', 'string', '32', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->removeColumn('tdh_consulta', 'email');
        $this->removeColumn('tdh_consulta', 'ip');
        $this->removeColumn('tdh_consulta', 'usuario_id');
        $this->removeColumn('tdh_consulta_respuesta', 'ip');
        $this->removeColumn('tdh_consulta_respuesta', 'usuario_id');
        $this->removeColumn('tdh_consulta_respuesta', 'consulta_id');
    }
}