<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('tdh_consulta_respuesta', 'usuario');
        $this->changeColumn('tdh_consulta_respuesta', 'descripcion', 'string', '4000', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->addColumn('tdh_consulta_respuesta', 'usuario', 'string', '32', array(
             'notnull' => '1',
             'default' => '',
             ));
    }
}