<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tdh_anuncio_pago', 'anuncio_id', 'integer', '4', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('tdh_anuncio_pago', 'anuncio_id');
    }
}