<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tdh_anuncio_pago', 'tdh_anuncio_pago_anuncio_id_tdh_anuncio_id', array(
             'name' => 'tdh_anuncio_pago_anuncio_id_tdh_anuncio_id',
             'local' => 'anuncio_id',
             'foreign' => 'id',
             'foreignTable' => 'tdh_anuncio',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tdh_anuncio_pago', 'tdh_anuncio_pago_anuncio_id', array(
             'fields' => 
             array(
              0 => 'anuncio_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tdh_anuncio_pago', 'tdh_anuncio_pago_anuncio_id_tdh_anuncio_id');
        $this->removeIndex('tdh_anuncio_pago', 'tdh_anuncio_pago_anuncio_id', array(
             'fields' => 
             array(
              0 => 'anuncio_id',
             ),
             ));
    }
}