<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('eh_foro_hilo_seguimiento', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'es_persistente' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'hilo_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'usuario_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('tdh_envio_social_pendiente', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'programado_para' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'servicio' => 
             array(
              'type' => 'enum',
              'notnull' => '1',
              'values' => 
              array(
              0 => 'facebook',
              1 => 'twitter',
              ),
              'default' => 'twitter',
              'length' => '',
             ),
             'nombre' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'descripcion' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'imagen' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'mensaje' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('tdh_critica', 'enviar_sociales');
        $this->removeColumn('tdh_evento', 'enviar_sociales');
        $this->removeColumn('tdh_noticia', 'enviar_sociales');
        $this->removeColumn('tdh_recurso', 'enviar_sociales');
        $this->addColumn('eh_foro_mensaje_privado', 'estado_notificacion', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->dropTable('eh_foro_hilo_seguimiento');
        $this->dropTable('tdh_envio_social_pendiente');
        $this->addColumn('tdh_critica', 'enviar_sociales', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('tdh_evento', 'enviar_sociales', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('tdh_noticia', 'enviar_sociales', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('tdh_recurso', 'enviar_sociales', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->removeColumn('eh_foro_mensaje_privado', 'estado_notificacion');
    }
}