<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('eh_foro_hilo_seguimiento', 'eh_foro_hilo_seguimiento_usuario_id_eh_auth_user_id', array(
             'name' => 'eh_foro_hilo_seguimiento_usuario_id_eh_auth_user_id',
             'local' => 'usuario_id',
             'foreign' => 'id',
             'foreignTable' => 'eh_auth_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('eh_foro_hilo_seguimiento', 'eh_foro_hilo_seguimiento_hilo_id_eh_foro_hilo_id', array(
             'name' => 'eh_foro_hilo_seguimiento_hilo_id_eh_foro_hilo_id',
             'local' => 'hilo_id',
             'foreign' => 'id',
             'foreignTable' => 'eh_foro_hilo',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('eh_foro_hilo_seguimiento', 'eh_foro_hilo_seguimiento_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->addIndex('eh_foro_hilo_seguimiento', 'eh_foro_hilo_seguimiento_hilo_id', array(
             'fields' => 
             array(
              0 => 'hilo_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('eh_foro_hilo_seguimiento', 'eh_foro_hilo_seguimiento_usuario_id_eh_auth_user_id');
        $this->dropForeignKey('eh_foro_hilo_seguimiento', 'eh_foro_hilo_seguimiento_hilo_id_eh_foro_hilo_id');
        $this->removeIndex('eh_foro_hilo_seguimiento', 'eh_foro_hilo_seguimiento_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->removeIndex('eh_foro_hilo_seguimiento', 'eh_foro_hilo_seguimiento_hilo_id', array(
             'fields' => 
             array(
              0 => 'hilo_id',
             ),
             ));
    }
}