<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tdh_oauth', 'tdh_oauth_usuario_id_eh_auth_user_id', array(
             'name' => 'tdh_oauth_usuario_id_eh_auth_user_id',
             'local' => 'usuario_id',
             'foreign' => 'id',
             'foreignTable' => 'eh_auth_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tdh_oauth', 'tdh_oauth_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tdh_oauth', 'tdh_oauth_usuario_id_eh_auth_user_id');
        $this->removeIndex('tdh_oauth', 'tdh_oauth_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
    }
}