<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('tdh_oauth', 'propietario', array(
             'fields' => 
             array(
              0 => 'usuario_id',
              1 => 'servicio',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('tdh_oauth', 'propietario', array(
             'fields' => 
             array(
              0 => 'usuario_id',
              1 => 'servicio',
             ),
             'type' => 'unique',
             ));
    }
}