<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tdh_sorteo_condicion', 'tdh_sorteo_condicion_sorteo_id_tdh_sorteo_id', array(
             'name' => 'tdh_sorteo_condicion_sorteo_id_tdh_sorteo_id',
             'local' => 'sorteo_id',
             'foreign' => 'id',
             'foreignTable' => 'tdh_sorteo',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tdh_sorteo_participante', 'tdh_sorteo_participante_sorteo_id_tdh_sorteo_id', array(
             'name' => 'tdh_sorteo_participante_sorteo_id_tdh_sorteo_id',
             'local' => 'sorteo_id',
             'foreign' => 'id',
             'foreignTable' => 'tdh_sorteo',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tdh_sorteo_usuario', 'tdh_sorteo_usuario_usuario_id_eh_auth_user_id', array(
             'name' => 'tdh_sorteo_usuario_usuario_id_eh_auth_user_id',
             'local' => 'usuario_id',
             'foreign' => 'id',
             'foreignTable' => 'eh_auth_user',
             ));
        $this->createForeignKey('tdh_sorteo_usuario', 'tdh_sorteo_usuario_participante_id_tdh_sorteo_participante_id', array(
             'name' => 'tdh_sorteo_usuario_participante_id_tdh_sorteo_participante_id',
             'local' => 'participante_id',
             'foreign' => 'id',
             'foreignTable' => 'tdh_sorteo_participante',
             ));
        $this->addIndex('tdh_sorteo_condicion', 'tdh_sorteo_condicion_sorteo_id', array(
             'fields' => 
             array(
              0 => 'sorteo_id',
             ),
             ));
        $this->addIndex('tdh_sorteo_participante', 'tdh_sorteo_participante_sorteo_id', array(
             'fields' => 
             array(
              0 => 'sorteo_id',
             ),
             ));
        $this->addIndex('tdh_sorteo_usuario', 'tdh_sorteo_usuario_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->addIndex('tdh_sorteo_usuario', 'tdh_sorteo_usuario_participante_id', array(
             'fields' => 
             array(
              0 => 'participante_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tdh_sorteo_condicion', 'tdh_sorteo_condicion_sorteo_id_tdh_sorteo_id');
        $this->dropForeignKey('tdh_sorteo_participante', 'tdh_sorteo_participante_sorteo_id_tdh_sorteo_id');
        $this->dropForeignKey('tdh_sorteo_usuario', 'tdh_sorteo_usuario_usuario_id_eh_auth_user_id');
        $this->dropForeignKey('tdh_sorteo_usuario', 'tdh_sorteo_usuario_participante_id_tdh_sorteo_participante_id');
        $this->removeIndex('tdh_sorteo_condicion', 'tdh_sorteo_condicion_sorteo_id', array(
             'fields' => 
             array(
              0 => 'sorteo_id',
             ),
             ));
        $this->removeIndex('tdh_sorteo_participante', 'tdh_sorteo_participante_sorteo_id', array(
             'fields' => 
             array(
              0 => 'sorteo_id',
             ),
             ));
        $this->removeIndex('tdh_sorteo_usuario', 'tdh_sorteo_usuario_usuario_id', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->removeIndex('tdh_sorteo_usuario', 'tdh_sorteo_usuario_participante_id', array(
             'fields' => 
             array(
              0 => 'participante_id',
             ),
             ));
    }
}