<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('tdh_sorteo_condicion', 'sufijo');
        $this->addColumn('tdh_sorteo', 'sufijo', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->addColumn('tdh_sorteo', 'url', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->addColumn('tdh_sorteo_condicion', 'sufijo', 'string', '255', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->removeColumn('tdh_sorteo', 'sufijo');
        $this->removeColumn('tdh_sorteo', 'url');
    }
}