<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tdh_sorteo', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'nombre' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'entradilla' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'aclaraciones' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '2000',
             ),
             'desde' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'hasta' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'participantes_min' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '1',
              'length' => '3',
             ),
             'participantes_max' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '3',
             ),
             'descripcion' => 
             array(
              'notnull' => '1',
              'default' => '',
              'type' => 'string',
              'length' => '50000',
             ),
             'descripcion_html' => 
             array(
              'notnull' => '1',
              'default' => '',
              'type' => 'string',
              'length' => '50000',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'tdh_sorteo_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('tdh_sorteo_condicion', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'nombre' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'sufijo' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'propietario' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'tipo' => 
             array(
              'type' => 'enum',
              'notnull' => '1',
              'values' => 
              array(
              0 => 'facebook',
              1 => 'twitter',
              ),
              'default' => 'twitter',
              'length' => '',
             ),
             'sorteo_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('tdh_sorteo_participante', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'numero' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '4',
             ),
             'nombre' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'token' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'domicilio' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'comentario' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '255',
             ),
             'sorteo_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'participante' => 
              array(
              'fields' => 
              array(
               0 => 'email',
               1 => 'sorteo_id',
               2 => 'token',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('tdh_sorteo_usuario', array(
             'usuario_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'participante_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'usuario_id',
              1 => 'participante_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('tdh_sorteo');
        $this->dropTable('tdh_sorteo_condicion');
        $this->dropTable('tdh_sorteo_participante');
        $this->dropTable('tdh_sorteo_usuario');
    }
}